project:
  type: website
  output-dir: docs
  preview: 
    port: 3141

website:
  title: "Learning University"
  navbar:
    left:

    - text: Calculus 1 
      menu:
        - text: Antiderivative
          href: Math/Calculus_1/antiderivative.qmd
        - text: Chap 4 Derivative Applications
          href: Math/Calculus_1/chap4_derivative_applications.qmd
        - text: Derivatives
          href: Math/Calculus_1/derivatives.qmd
        - text: Formulas
          href: Math/Calculus_1/formulas.qmd
        - text: Integrals
          href: Math/Calculus_1/integrals.qmd
        - text: Limits
          href: Math/Calculus_1/limits.qmd
        - text: Trig
          href: Math/Calculus_1/trig.qmd

    - text: Multivariable Calculus 
      menu: 
        # - text: Calculus 1-3
        #   href: Math\Multivariable_Calculus\OpenStax_Calculus_Books.qmd
        - text: Master Notes
          href: Math/Multivariable_Calculus/Master_Notes_Multivariable_Calculus.qmd

    - text: Linear Algebra 
      href: Math\Linear_Algebra\linear_algebra.qmd

    - text: Data Science
      menu: 
        - text: DAX 
          href: data_science/dax/dax.qmd
        - text: RPackages 
          href: data_science/rpackages.qmd

    - text: Latex 
      href: other/latex_notes.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

