project:
  type: website
  output-dir: docs
  preview: 
    port: 3141

website:
  title: "Learning University"
  navbar:
    left:
      - text: "Limits"
        href: calc1/limits.qmd
      - text: "Derivatives"
        href: calc1/derivatives.qmd
      - text: "Integrals"
        href: calc1/integrals.qmd
      - text: "Common Formulas"
        href: calc1/formulas.qmd
      - text: "Common Errors"
        href: calc1/common_errors.qmd
      - text: "Other"
        href: other_subjects\1through4.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

