project:
  type: website
  output-dir: docs
  preview: 
    port: 3141

website:
  title: "Learning University"
  navbar:
    left:
    - text: Math
      menu: 
        - text: Limits
          href: Math/limits.qmd
        - text: "Derivatives"
          href: Math/derivatives.qmd
        - text: "Integrals"
          href: Math/integrals.qmd
        - text: Common Formulas
          href: Math/formulas.qmd
        - text: "Common Errors"
          href: Math/common_errors.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

