---
title: Week 04 Interview Follow-up and Cover Letter
format: html
---

[W04 Study: Interview Follow-up and Cover Letter](https://byui.instructure.com/courses/221164/pages/w04-study-interview-follow-up-and-cover-letter?module_item_id=28018348)


- Uhh, [this book](http://mcom320.net/index.html) looks like a fantastic resource
    - this book is about business writing
        - “A sentence should contain no unnecessary words, a paragraph no unnecessary sentences, for the same reason that a drawing should have no unnecessary lines and a machine no unnecessary parts. Vigorous writing is concise.” —Strunk and White, Elements of Style
- This is chapter three, "Build: Be Clear and Concise"
    - Strong Phrases
        - Try to become allergic to using them
    - Prepisitions are connector words. 
    - "Avila is a walled city" is prefered over "Avila is a city with a wall around it." I'm thinking of these as *levels of inteligence*.
- What is English class? Just like how I'm thinking of the math tree
    - grammer
    - vocabularly
    - literature
    - Writing essays
    - Types: 
        - Business writing 
- Use this knowledge for the script of my videos
- WHY should everyone do these things I'm receiving revelation for? Because it is *freeing*, *enabling*, ....

- [How to Write the Perfect Cover Letter for an Internship (Plus, an Example!)](https://www.themuse.com/advice/how-to-write-cover-letters-for-internship-example)
    - Avoid being impressed in a generic way. If you can say the same thing about another company then you’re not being specific enough. In other words, don’t say: “I’m impressed that Company X is a market leader in clean-tech.” Instead, say: “Company X’s unique approach to removing plastic pollution from the ocean by using currents and robotic traps is fascinating.”
    - 

 



[W04 Draft: Interview Follow-up](https://byui.instructure.com/courses/221164/assignments/10123523?module_item_id=28018362)

[W04 Peer Review: Interview Follow-up](https://byui.instructure.com/courses/221164/assignments/10123581?module_item_id=28018380)

[W04 Polished Draft: Interview Follow-up](https://byui.instructure.com/courses/221164/assignments/10123599?module_item_id=28018400)

[W04 Employment Portfolio: Cover Letter](https://byui.instructure.com/courses/221164/assignments/10123553?module_item_id=28018416)

[W04 Quiz: NoRedInk](https://byui.instructure.com/courses/221164/pages/w04-quiz-noredink?module_item_id=28018430)
