---
title: "34 In Quest of Reformation Part 1"
format: html
---



## The Conciliar Movement 
- Two popes at the time: Gregory XII the Roman Pope, and the Pisan Pope John XXIII 
- the thinking was that a council would determine who was the legitimate Pope
- How should we conviene this council? It wouldn't be put on by one side, they would choose their Pope. To fix this, the cardinals of both parties worked together to gather in Pisa in 1409
    - insert picture of leaning tower of pisa
- both parties tried to thwart each other's claim
- What was the result of this concil? It was decided that both of the popes were unworthy to be Pope.
- this council had the backing of each side as well as the courts in Europe. 
- The next issue the council moved onto was that of simony and other issues in the church. 
    - this is 
- Alexander V was elected by the council to be the new pope

- The council thought this would bring about a productive ending, but it only made the schism worse. 
- Europe mostly accepted Alexander to be the pope, but the other two had a big enough base of supporters to cause issues. Also, Alexander died less than a year after becoming Pope. 
- John XXIII was elected to take his place by the cardinals.
- Another council gathered at Constance in 1414. There was political termoil and John was sentanced to prison for the rest of his life and Gregory abdicated. 
-  



## John Wycliffe 



## John Huss 

- from the Czech Republic (1362-1415)
- lots going on in his country about to many Germans there. 
- My 3 favorite things from Huss: 
    - "He thus came to the conclusion that the Bible is the final authority by which the pope as well as any Christian is to be judged. A pope who does not obey the Bible is not to be obeyed."
    - Huss, who had bought an indulgence twenty years earlier, by then had come to the conclusion that only God could grant forgiveness, and that to sell what comes only from God is usurping God’s power
    - Was against the sending of Christians to fight in crusaides 
- Excomunicated more than once
- He eventually left the public scene and lived in the country side. He continued his writings of the need for reformation whist living there. 
- He was invited to attend a Great Council in Constance from Sigismund. This council was supposed to be a fresh start for the church, so he was ega to attend. 
- He was promised safety there but he was turned on. He was condemed as a heratic and sentance to the slammer. 
- In pleading his cause, he said, "I appeal to Jesus Christ, the only judge who is almighty and completely just. In his hands I place my cause, since he will judge each, not on the basis of false witnesses and erring councils, but on truth and justice."
-  The Bohemians were indignant after hearing of his myrtr, and almost unanimously repudiated the council. Four hundred and fifty-two noblemen gathered in solemn assembly and announced their agreement with Huss, that an unworthy pope ought not be obeyed. The council countered by ordering that the University of Prague be dissolved
- Four articles came of his death as the Bohemian's resisted the church. 
- The church rejected them at first but after failed crusaides, they compromised with them. Very sad
