---
title: 1through4
---


1 
 
The Call for Reformation 
 
The dissolution is such, that the souls entrusted to the clergy receive great damage, for we are told that the majority of the 
clergy are living in open concubinage, and that if our justice intervenes in order to punish them, they revolt and create a scan- 
dal, and that they despise our justice to the point that they arm themselves against it. 
ISABELLA OF CASTILE, ON NOVEMBER 20, 1500 
 
As the fifteenth century came to a close, it was clear that the church was in need of profound reformation, and that many longed 
for it. The decline and corruption of the papacy was well known. After its residence in Avignon, where it had served as a tool of 
French interests, the papacy had been further weakened by the Great Schism, which divided Western Europe in its allegiance to 
two—and even three—popes. At times, the various claimants to the papal see seemed equally unworthy. Then, almost as soon 
as the schism was healed, the papacy fell into the hands of men who were more moved by the glories of the Renaissance than 
by the message of the cross. Through war, intrigue, bribery, and licentiousness, these popes sought to restore and even to 
outdo the glories of ancient Rome. As a result, while most people still believed in the supreme authority of the Roman see, many 
found it difficult to reconcile their faith in the papacy with their distrust for its actual occupants. 
Corruption, however, was not limited to the leadership in Rome. The councils that had been convened as a means to reform 
and to end the Great Schism were able to end the schism, but not to bring about the needed reformation. Furthermore, even in 
ending the schism the conciliar movement showed its own flaws, for there were soon two rival councils—just as before there 
had been two or even three rival popes, and conciliarism had failed miserably in the task of bringing about the much-needed re- 
form. One of the reasons for such failure was that several of the bishops sitting in the councils were themselves among those 
who profited from the existing corruption. Thus, while the hopeful conciliarist reformers issued anathemas and decrees against 
absenteeism, pluralism, and simony—the practice of buying and selling ecclesiastical positions—many who sat on the councils 
were guilty of such practices, and were not ready to give them up. 
Such corrupt leadership set the tone for most of the lesser clergy and the monastics. While clerical celibacy was the law of the 
church, there were many who broke it openly; and bishops and local priests alike—and even some popes—flaunted their illegit- 
imate children. The ancient monastic discipline was increasingly relaxed as convents and monasteries became centers of 
leisurely living. Monarchs and the high nobility often provided for their illegitimate offspring by having them named abbots and 
abbesses, with no regard for their monastic vocation or lack of it. The commitment to learning for which monastic houses had 
been famous also declined, and the educational requirements for the local clergy fell to practically nil. 
The conciliar movement had waned, and with it also the hope that a general council of the church could produce the much- 
needed reformation. A sign of this was the Fifth Lateran Council, which was convoked by Pope Julius II, supposedly in order to 
reform the church, but in truth in an effort to regain the political control the papacy had been losing. The council convened in 
1512, and by the time it disbanded in 1517 it had achieved little beyond decreeing an extraordinary taxation to span the next three 
years—theoretically, in order to raise funds for a new crusade—reaffirming the authority of the pope in the face of French at- 
tempts to limit such authority, and insisting on the power and dignity of bishops and other prelates. It should be noted that the 
council adjourned in March of 1517, a few months before the beginning of the Protestant Reformation. 
In such circumstances, even the many priests and monastics who wished to be faithful to their calling found this to be ex- 
ceedingly difficult. How could one practice asceticism and contemplation in a monastery that had become a house of leisure 
and a meeting place for fashionable soirées? How could a priest resist corruption in his parish, when he himself had been 
forced to buy his position? How could the laity trust a sacrament of penance administered by a member of the clergy who 
seemed to have no sense of the enormity of sin? The religious conscience of Europe was divided within itself, torn between trust 
in a church that had been its spiritual mother for generations, and the patent failures of that church. 
But it was not only at the moral level that the church seemed to be in need of reformation. Some among the more thoughtful 
Christians were becoming convinced that the teachings of the church had also gone astray. The fall of Constantinople, half a 
century earlier, had flooded Western Europe, and Italy in particular, with scholars whose views were different from those that 
were common in the West. The manuscripts these scholars brought with them alerted Western scholars to the many changes 
and interpolations that had taken place in the copying and recopying of ancient texts. New philosophical outlooks were also 
introduced. Greek became more commonly known among Western scholars, who could now compare the Greek text of the New 
Testament with the commonly used Latin Vulgate. From such quarters came the conviction that it was necessary to return to the 
sources of the Christian faith, and that this would result in a reformation of existing doctrine and practice. 
Although most who held such views were by no means radical, their call for a return to the sources tended to confirm the ear- 
lier appeals by reformers such as Wycliffe and Huss. The desire for a reformation in the doctrine of the church did not seem so 
out of place if it were true that such doctrine had changed through the centuries, straying from the New Testament. The many 
followers of those earlier reformers still had in England, Bohemia, and other areas now felt encouraged by scholarship which, 
while not agreeing with them on their more radical claims, confirmed their basic tenet: that it was necessary to return to the 
sources of Christianity, particularly through the study of Scripture. 
To this was added the discontent of the masses, which earlier had found expression in apocalyptic movements like the one 
led by Hans Böhm. The economic conditions of the masses, far from improving, had worsened in the preceding decades. The 
peasants in particular were increasingly exploited by the landowners. While some monastic houses and church leaders still prac- 
ticed acts of charity, most of the poor no longer had the sense that the church was their defender. On the contrary, the 
tiousness of prelates, their power as landowners, and their support of increasing inequality were seen by many as a betrayal of 
the poor, and eventually as a sign that the Antichrist had gained possession of the church. The ferment brewing in such quarters 
periodically broke out in peasant revolts, apocalyptic visions, and calls for a new order. 
Meanwhile, the ancient feudal system was coming to an end. First France, and then England and Spain, saw the development 
of powerful monarchies that forced the nobility to serve the ends of the nation as a whole. The sovereigns of such states felt the 
need to limit and control the power of the prelates, many of whom were also feudal rulers of vast areas. As France had earlier led 
in the suppression of the Templars, Spain now felt compelled to bring the ancient military orders, such as Calatrava and San- 
tiago, under royal supremacy; and to that end King Ferdinand was made their grand master. Areas that did not enjoy the same 
unity, such as the Netherlands and Germany, seethed with nationalist discontent and dreams of union and independence. Latin, 
which earlier had been a common bond for much of Western Europe, was increasingly limited to ecclesiastical and scholarly cir- 
cles, while the various vernacular languages came to be regarded as equally respectable. Indeed, the fifteenth and sixteenth cen- 
turies were the formative period for most of the literary languages of Western Europe. Nationalism, which had begun to develop 
centuries earlier, found expression in these languages, and soon became the order of the day, both in those nations that had 
achieved political unity and in those that still fretted under feudal disunion and foreign dominance. Such sentiments in turn 
undermined the ancient dream of “one flock under one shepherd,” which now appeared to many as little more than an excuse 
for foreign intervention. 
 
 
The Convento de Santo Domingo, in Avila, served as the headquarters for Torquemada’s inquisitorial activities. 
 
In some areas, the growing power of the monarchs, the divergent opinions and ideas in a time of intellectual unrest, and 
tration with the actual life of the church, led to an increase in the powers and activities of the Inquisition. Already in the Middle 
Ages it was not uncommon for bishops to act as inquisitors, investigating the theological opinions of their flocks, seeking to 
correct those whose views were considered heretical, and severely punishing the teachers and leaders who espoused those 
views. But in the fifteenth century, particularly in Spain, the powers and activity of the Inquisition rose to new heights. The Inqui- 
sition, normally under papal authority and in the later Middle Ages used mostly as a tool of papal policy, was placed by the pope 
under the authority of Ferdinand and Isabella. The Dominican friar Tomás de Torquemada, who was known for his uncompro- 
mising love for orthodoxy, was appointed to head the Inquisition in Castile, and his name has become famous for the zeal with 
which he persecuted those whom he considered heretics. These were mostly Jews who had been converted under duress, and 
who were now accused of “Judaizing.” 
 
 
The tortures of the Inquisition included a form of what later would be called “water-boarding.” 
 
As we shall see, at that time there was a concerted effort to reform the church on the part of Queen Isabella and her confessor 
Francisco Jiménez de Cisneros. During Isabella’s reign, and with the firm encouragement of Jiménez, the pressure on Jews and 
“Judaizing” Christians became increasingly severe. Finally, in 1492, it was decreed that all Jews must either accept baptism or 
leave all territories under Isabella and Ferdinand. Most refused to be baptized, even though it meant exile and the loss of most 
of their possessions. Although exact figures are not available, it seems that approximately two hundred thousand Spaniards of 
the Jewish faith were thus condemned to exile—which in many cases led to death, capture by pirates, and other such misfor- 
tunes. 
Shortly before the promulgation of the royal decree against Jews, Granada had fallen to Castilian arms. This was the last 
Moorish stronghold in the peninsula, and the terms of surrender included freedom for the Muslims to continue practicing their 
religion. But soon Jiménez and his representatives were seeking the forced conversion of the Moors, who saw no alternative but 
rebellion. This was drowned in blood. But resistance continued, and eventually it was decreed that all Moors had to choose be- 
tween baptism and exile. When it became clear that there would be a massive exodus, a new edict was issued, forbidding the 
Moors from leaving the country, and forcing baptism on them. After such unwilling conversions, the Inquisition was kept busy 
tracking down those who persisted in their Muslim beliefs and practices. Jiménez, who had been made Inquisitor General, took 
this task to heart. In 1516, after the death of both Ferdinand and Isabella, he was also made regent, and sought to use his power 
to force the “converted” Moors to abandon their traditional garb and other customs. In this he failed, and again the kingdom 
was shaken by rebellion and bloodshed. 
Then came the Protestant Reformation and the “discovery” of the New World, and both led to broader actions by the Inqui- 
sition. As we shall see, in Europe this was part of the Catholic Reformation, which used the Inquisition as one of its tools to pre- 
vent the spread of Protestantism. In the New World, the powers of the Inquisition were eventually employed also to prevent and 
punish interlopers from other European nations. 
The means of torture used during the Inquisition, and the manner in which it was exploited for political reasons as well as for 
personal gain and vengeance, are well known, and their memory would long survive as a prime example of the dangers and 
consequences of religious extremism and obscurantism. 
 
An old world was passing away, and a new one was being born to take its place. In this illustration from one of Galileo’s works, he is 
depicted as discussing the universe with Ptolemy and Copernicus. 
 
While it does not justify it, the context within which the Inquisition took place must be understood, including other momen- 
tous events that were changing Western Europe’s worldview and creating an atmosphere of both expectation and uncertainty. 
New worlds were being discovered beyond the Western horizon. Travel to the Far East was becoming increasingly common. The 
flat earth around which the sun and the stars revolved became a relic of the past. Great advances were being made in medicine, 
mathematics, and physics. And all this was made readily available to scholars in various areas by means of the printing press, 
which was coming into its own precisely at that time. 
An old world was passing away, and a new one was being born. It was unavoidable that the church too would feel the impact 
of the new times and that, just as new ways of being human were emerging, new ways of being Christian would also emerge. Ex- 
actly how this was to be done, however, was open to debate. Some sought to reform the old church from within, while others 
lost all hope for such reformation, and openly broke with the papacy. In an age of such turmoil, many sincere Christians went 
through profound soul searching that eventually led them to conclusions and positions they could not have predicted. Others, 
equally sincere and devout, came to opposite conclusions. The resulting disagreements and conflict marked the entire age that 
we now call the Reformation of the sixteenth century. 
As the Middle Ages drew to a close, many advocates of reform were convinced that the greatest ill of the church was the 
obscurantism of what soon would be called the Dark Ages. The printing press, the influx of Byzantine scholars, and the redis- 
covery of the artistic and literary legacies of antiquity gave credence to the hope that the furtherance of scholarship and educa- 
tion would produce the much-needed reformation of the church. If at some point in the past centuries practices had been intro- 
duced that were contrary to original Christian teaching, it seemed reasonable to surmise that a return to the sources of Chris- 
tianity—both biblical and patristic—would do away with such practices. 
This was the program of the humanist reformers. In this context, the term humanist does not refer primarily to those who 
value human nature above all else, but rather to those who devote themselves to the “humanities,” seeking to restore the literary 
glories of antiquity. The humanists of the sixteenth century differed greatly from one another, but all agreed in their love of clas- 
sical letters. Long before the Protestant Reformation broke out, there was a large network of humanists who carried a vast corre- 
spondence among themselves and who hoped that their work would result in the reformation of the church. Their acknowl- 
edged leader, respected by many and known as the Prince of Humanists, was Desiderius Erasmus of Rotterdam. 
Erasmus was the illegitimate offspring of a priest and a physician’s daughter, and throughout his life felt burdened by his 
humble origins. Reared in the midst of the bustling commercial activity of Holland, his opinions came to reflect the common 
values of the bourgeoisie: tolerance, moderation, stability, and so forth. He studied some scholastic theology, but soon came to 
despise its excessive subtlety and seemingly idle curiosity. He then decided to turn his attention to classical literature, which 
was enjoying a revival of interest. In a later visit to England, he became part of a circle of humanists interested in the reformation 
of the church, and these introduced him to the study of Scripture and of early Christian literature, which he saw as captive to the 
scholastics. It was at that time that he decided to perfect his rudimentary knowledge of Greek, which he soon mastered. Mean- 
while, he published the Enchiridion militis Christiani—Dagger (or Handbook) of the Christian Soldier. There, using military 
metaphors, he expounded on what he took to be the Christian life, and the resources available to the “soldier of Christ.” 
 
Erasmus, the “prince of humanists,” as Albrecht Dürer saw him in 1526. The Greek words affirm that the works of Erasmus himself 
convey a better portrait than Dürer’s. 
 
As a young man, Erasmus had studied under the Brethren of the Common Life, and their “modern devotion” had had a pro- 
found impact on him. Now, combining the humanist spirit to that devotion, he came to describe Christianity as above all a de- 
cent, moderate, and balanced life. The commandments of Jesus he saw as similar to the best precepts of Stoicism and Pla- 
tonism: Their purpose is to subject passion to the rule of reason. This is to be achieved through a fairly ascetic discipline, al- 
though this discipline must not be confused with monasticism. The monastic withdraws from the common life of the world; the 
true “soldier of Christ” trains for practical and daily life in the midst of human affairs. What the church needs, in order to be re- 
formed, is for Christians to practice this discipline, and to abandon the vices of the pagans. In this reference to pagan vices, 
Erasmus had in mind the evil example set by the popes of the Renaissance, who had preferred comparison with Jupiter or with 
Julius Caesar than with Jesus or St. Peter. He therefore rejected the pomp and the quest for earthly glories that characterized 
much of the life of the church in his time, and called for a lifestyle of greater simplicity. This did not mean, however, a mere re- 
vival of the monastic spirit. He had much to say against monks and monasteries, which had become havens of idleness and 
ignorance. But he also rejected the monastic ideal as based on the unacceptable distinction between the precepts of Jesus, 
which all must obey, and his “counsels of perfection,” addressed to monastics in particular. Such distinction, while encouraging 
some to radical obedience, implied that common Christians were somehow not also “soldiers of Christ,” called to complete 
obedience. 
Erasmus viewed such obedience as more important than doctrine. He did believe that doctrines were 
significant, and he held to traditional Christian orthodoxy on matters such as the incarnation and the Trinity. But he insisted that 
righteousness was more important than orthodoxy, and he frequently attacked friars who were capable of subtle theological dis- 
cussions but whose lives were scandalous. 
On the other hand, the true Christian life is one of inwardness. Profoundly influenced by Platonism—and by ancient Christian 
writers who had suffered the same influence—Erasmus was convinced that the Christian struggle was an inner one. While out- 
ward means, such as the sacraments, were important and should not be discarded, their significance was in their inner mean- 
ing, in the message they conveyed to the secret heart of the believer. As he would say of baptism, “what good is it to be out- 
wardly sprinkled with holy water, if one is filthy within?” 
In short, what Erasmus sought was the reformation of customs, the practice of decency and moderation, an inner devotion 
shaped by learning and meditation, and a church that encouraged these things. Although his birth was quite humble, he even- 
tually won the admiration of scholars throughout Europe who shared similar hopes, and whose mouthpiece he became. Among 
his admirers were many in the nobility and even some crowned heads. His followers served as secretaries and mentors in some 
of the most powerful courts in Europe. The reformation he advocated seemed about to take place. 
Then the Protestant Reformation broke out. Spirits were inflamed. Tolerance and moderation became increasingly difficult. It 
was no longer a matter of reforming customs, or of clarifying some aspects of Christian theology that might have gone astray, 
but rather of radically shifting some of the fundamental premises of traditional Christianity. Partisans on both sides sought the 
support of Erasmus, who preferred to stay out of a conflict in which passion seemed to have replaced reason. Eventually, he 
broke with Luther and his followers, as we shall see later on. But still he refused to support the Catholics in their attacks against 
the Protestants. To the very end, he had admirers in both camps but very few followers. From his study, while others called for 
inquisitorial intolerance, he continued calling for tolerance and moderation, for a reformation after the humanist design, and for 
the ancient virtues of the Stoics and the Platonists. Few paid heed to him, at least during his lifetime, and he would complain, “I 
detest dissension, because it goes both against the teachings of Christ and against a secret inclination of nature. I doubt that ei- 
ther side in the dispute can be suppressed without grave loss. It is clear that many of the reforms for which Luther calls are ur- 
gently needed. My only wish is that now that I am old I be allowed to enjoy the results of my efforts. But both sides reproach me 
and seek to coerce me. Some claim that since I do not attack Luther I agree with him, while the Lutherans declare that I am a 
coward who has forsaken the gospel.”¹ But centuries later, after passions had subsided, both Protestants and Catholics would 
agree that his was a great mind and a great heart, and that all had something to learn from him.


2 
 
Martin Luther: Pilgrimage to Reformation 
 
Many have taken the Christian faith to be a simple and easy matter, and have even numbered it among the virtues. This is be- 
cause they have not really experienced it, nor have they tested the great strength of faith. 
MARTIN LUTHER 
 
Throughout the history of Christianity, few have been the object of as much debate as Martin Luther has been. Some describe 
him as the ogre who destroyed the unity of the church, the wild boar that trampled the Lord’s vineyard, a renegade monk who 
spent his life shattering the very foundations of monasticism. For others, he is the great hero through whose efforts the preach- 
ing of the pure gospel was restored, the champion of biblical truth, and the reformer of a corrupt and apostate church. In recent 
years, however, there has been a growing mutual understanding among Christians of different persuasions. As a result of more 
balanced studies of Luther, Catholics as well as Protestants have been led to amend opinions that had resulted, not from histor- 
ical research, but from the heat of polemics. Now few doubt Luther’s sincerity, and many Catholic historians affirm that his 
protest was amply justified, and that he was right on many points of doctrine. On the other hand, few Protestant historians con- 
tinue to view Luther as the gigantic hero who almost single-handedly reformed Christianity, and whose sins and errors were only 
of minor importance. 
Luther appears to have been an erudite and studious man who was also uncouth and even rude in his manner. Perhaps this 
helped him express his very profound theological points in a manner that found ready response among the masses. He was sin- 
cere in his faith to the point that it became a passion burning within him, which he could also be vulgar in expressing. Nothing 
mattered to him as much as his faith and his obedience to God. Once he became convinced that God wished him to pursue a 
certain course of action, he followed it to its ultimate consequences. He was clearly not the sort of disciple who, having put a 
hand to the plow, looks back. His use of language—both Latin and German—was masterful, although he was inclined to under- 
line the importance of a particular assertion by exaggerating it to the point of distortion. Once convinced of the truth of his 
cause, he was ready to face the most powerful lords of his time. But the very depth of his conviction, his passionate stance on 
truth, and his tendency to exaggerate led him to utter expressions and take positions that he or his followers would later regret. 
 
 
This painting by Lucas Cranach (1526), now in the National Museum of Stockholm, is probably the most authentic extant portrait of 
Luther. 
 
On the other hand, much of Luther’s impact was due to circumstances that he neither created nor controlled, and of whose 
role in the process of reformation he himself was only dimly aware. The invention of the movable type printing press gave his 
writings a widespread audience they otherwise would not have had—in fact, Luther was the first to make full use of the value of 
printing as a medium for propaganda, and to write with the printed page in mind. The growing German nationalist sentiment of 
which he himself partook offered unexpected but very valuable support. Many humanists who hoped for reformation, while dis- 
agreeing with many of Luther’s tenets and methods, insisted that he should not be condemned without a hearing, as had hap- 
pened earlier to John Huss. Political circumstances at the outset of the Reformation also prevented Luther’s immediate condem- 
nation, and by the time civil and ecclesiastic authorities were ready to intervene it was too late to quiet the storm. On studying 
Luther’s life and work, one thing is clear: the much-needed reformation took place, not because Luther decided that it would be 
so, but rather because the time was ripe for it, and because the Reformer and many others with him were ready to fulfill their 
historical responsibility.


THE LONG QUEST 
Luther was born in 1483, in Eisleben, Germany. His father, of peasant origin, had first become a miner and then the owner of 
several foundries. Young Martin’s childhood was not a happy one. His parents were extremely severe, and many years later he 
would still speak bitterly of some of the punishments he had suffered. Throughout his life he was prey to periods of depression 
and anxiety, and some scholars suggest that this was due to the excessive austerity of his early years. His first experiences at 
school were no better, and he later spoke of having been whipped for not knowing his lessons. Although the importance of such 
early experiences ought not be exaggerated as the sole explanation for the course of Luther’s life, there is no doubt that they left 
a deep imprint on his character. 
In July 1505, when almost twenty-two years of age, Luther joined the Augustinian monastery at Erfurt. Many causes led to this 
decision. Two weeks earlier, in the midst of a thunderstorm, he had felt overwhelmed by the fear of death and hell, and he had 
promised St. Anne that he would become a monk. According to his own later explanation, it was his harsh upbringing that led 
him to the monastery. His father had planned for him a career in law, and had not spared efforts so that he could have the 
necessary education. But Luther had no desire to become a lawyer, and therefore it is possible that Luther, though not entirely 
aware of his motives, was interposing a monastic vocation between his father’s plans and his own inclinations. Upon hearing of 
his son’s decision, the older Luther was incensed, and took his own good time in forgiving what appeared to him as a betrayal 
of his lofty goals for his son. Ultimately, however, Luther was led to the monastery by a concern for his own salvation. The 
theme of salvation and damnation permeated the atmosphere in which he lived. The present life was little more than a prepa- 
ration and testing for the one to come. It seemed foolish to devote oneself to gaining prestige and riches in the present, through 
the practice of law, to the detriment of life everlasting. Luther therefore entered the monastery as a faithful child of the church, 
with the clear purpose of making use of the means of salvation offered by that church, of which the surest was the monastic life 
of renunciation. 
During the year of his novitiate, Luther was convinced that he had made a wise decision, for he felt happy and at peace with 
God. His superiors promptly recognized his unusual abilities, and decided that he should become a priest. Luther himself later 
wrote about the overwhelming experience of celebrating his first mass, when he was gripped by terror upon thinking that he was 
holding and offering nothing less than the very body of Christ. That feeling of terror then became increasingly frequent, for he 
felt unworthy of God’s love, and he was not convinced that he was doing enough to be saved. God seemed to him a severe 
judge—much the same as his father and his teachers had been at an earlier time—who, in the final judgment, would ask for an 
account and find him wanting. In order to be saved from the wrath of such a God, one must make use of all the means of grace 
offered by the church. 
But those means were not sufficient for someone as deeply religious, sincere, and passionate as Luther. Good works and the 
sacrament of penance were supposed to suffice for the young friar’s need to be justified before God. But they did not. Luther 
had an overpowering sense of his own sinfulness, and the more he sought to overcome it, the more he became aware of sin’s 
sway over him. It is mistaken to suppose that he was not a good monk, or that his life was licentious or immoral. On the con- 
trary, he sought to obey his monastic vows to the fullest. He would repeatedly punish his body, as recommended by the great 
teachers of monasticism. And he went to confession as often as possible. But such practices did not allay his fear of damnation. 
If sins had to be confessed to be forgiven, there was always the horrifying possibility that he might forget some sin, and thus 
lose the reward after which he was so diligently striving. He therefore spent hours listing and examining all his thoughts and ac- 
tions, and the more he studied them the more sin he found in them. There were times when, at the very moment of leaving the 
confessional, he realized that there was some sin that he had not confessed. He would then grow anxious and even desperate, 
for sin was clearly more than conscious actions or thoughts. It was a condition, a way of being, something that went far beyond 
the individual sins one could confess to a priest. Thus, the very sacrament of penance, which was supposed to bring relief to his 
sense of sinfulness, actually exacerbated it, leaving him in a state of despair. 
His spiritual advisor then recommended the reading of the great teachers of mysticism. As we have already seen, toward the 
end of the Middle Ages (partially as a response to the corruption of the church) there was a great upsurge in mystical piety, 
which offered an alternative path through which to approach God. Luther resolved to follow that path, not because he doubted 
the authority of the church, but because that authority, in the person of his confessor, advised him to do so. 
Mysticism captivated him for a time—as monasticism had earlier. Perhaps here he would find the path to salvation. But soon 
that path became another blind alley. The mystics affirmed that all one had to do was to love God, and that all the rest would fol- 
low as a result of that love. This was a word of liberation for Luther, for it was no longer necessary to keep a strict account of all 
his sins, as he had so eagerly endeavored to do, to be rewarded only by failure and despair. But he soon discovered that loving 
God was not an easy matter. If God was like his father and his teachers, who had beaten him to the point of drawing blood, how 
could he love such a God? Eventually, Luther came to the terrifying conclusion that what he felt for God was not love, but ha- 
tred! 
There was no way out of such difficulties. In order to be saved, one must confess one’s sins, and Luther had discovered that, 
in spite of his best efforts, his sin went far beyond what he could confess. If, as the mystics claimed, it sufficed to love God, this 
was no great help, for Luther had to acknowledge that he could not love the just God that demanded an account of all his ac- 
tions. 
At that point, his confessor, who was also the superior, took a bold step. Normally, one would suppose that a priest who was 
going through such a crisis as Luther’s should not be made a pastor and teacher for others. But that was precisely what his con- 
fessor decided he should be. Centuries earlier, Jerome had found in his Hebrew studies an escape from temptation. Although 
Luther’s problems were different from Jerome’s, perhaps study, teaching, and pastoral responsibilities would have a similar ef- 
fect on him. Therefore, Luther was ordered, much against his expectations, to prepare to teach Scripture at the new University of 
Wittenberg. 
Protestant folklore has it that as a friar Luther did not know the Bible, and that it was only at the time of his conversion, or 
shortly before, that he began to study it. This is false. As a monk who had to follow the traditional hours of prayer, Luther knew 
the Psalter by heart. Besides, in 1512, after studies that included the Bible, he received his doctorate in theology. 
When Luther found himself forced to prepare lectures on the Bible, he began seeing new meanings in it, along with the possi- 
bility that such meanings would provide an answer to his spiritual quest. In 1513, he began to lecture on the Psalms. Since he 
had spent years reciting the Psalter, always within the context of the liturgical year—which centers on the main events in the life 
of Christ—Luther interpreted the Psalms Christologically. When the Psalmist speaks in the first person, Luther took this to be 
Christ speaking about himself. Therefore, in the Psalter, Luther saw Christ undergoing trials similar to his own. This was the 
beginning of his great discovery. By itself, it could have led Luther to the commonly held notion that, while God the Father ex- 
acts obedience and righteousness, God the Son loves us and works for our forgiveness. But Luther had studied theology, and 
knew that such dichotomy within the Godhead was unacceptable. Therefore, while he found consolation in Christ’s sufferings, 
this did not suffice to cure his anguish and despair. 
The great discovery probably came in 1515, when Luther began lecturing on the Epistle to the Romans. He later declared that it 
was in the first chapter of that epistle that he found the solution to his difficulties. That solution did not come easily. It was not 
simply a matter of opening the Bible one day and reading that “the just shall live by faith.” As he tells the story, the great dis- 
covery followed a long struggle and bitter anguish, for Romans 1:17 begins by declaring that, in the gospel, “the righteousness of 
God is revealed.” According to this text, the gospel is the revelation of the righteousness—the justice—of God. But it was pre- 
cisely the justice of God that Luther found unbearable. How could such a message be gospel, good news? For Luther, good 
news would have been that God is not just, meaning that God does not judge sinners. But, in Romans 1:17, the good news and 
the justice of God are indissolubly linked. Luther hated the very phrase “the justice of God,” and spent day and night seeking to 
understand the relationship between the two parts of that single verse, which, after declaring that in the gospel “the justice of 
God is revealed,” affirms that “the righteous shall live by faith.” 
The answer was surprising. Luther came to the conclusion that the “justice of God” does not refer, as he had been taught, to 
the punishment of sinners. It means rather that the “justice” or “righteousness” of the righteous is not their own, but God’s. 
The “righteousness of God” is that which is given to those who live by faith. It is given, not because they are righteous, nor be- 
cause they fulfill the demands of divine justice, but simply because God wishes to give it. Thus, Luther’s doctrine of “justifi- 
cation by faith” does not mean that what God demands of us is faith, as if this were something we have to do or achieve, and 
which God then rewards. It means rather that both faith and justification are the work of God, a free gift to sinners. As a result of 
this discovery, Luther tells us, “I felt that I had been born anew and that the gates of heaven had been opened. The whole of 
Scripture gained a new meaning. And from that point on the phrase ‘the justice of God’ no longer filled me with hatred, but 
rather became unspeakably sweet by virtue of a great love.” 


THE STORM BREAKS 
Although later events revealed another side to his personality, until this time Luther seems to have been quite reserved, devoted 
to his studies and to his spiritual struggle. His great discovery, while bringing him to a new understanding of the gospel, did not 
immediately lead him to protest against the church’s interpretation of Christianity. On the contrary, our friar continued in his 
teaching and pastoral duties and, although there are indications that he taught what he had recently learned, he did not frame it 
in opposition to the traditional teaching of the church. Moreover, he does not seem to have been aware of the radical contra- 
diction between his discovery and the entire penitential system that was so fundamental to accepted theology and piety. 
Through quiet persuasion, Luther brought most of his colleagues at the University of Wittenberg over to his way of thinking. 
When he became convinced that he must challenge traditional views, he composed ninety-seven theses designed to be debated 
in an academic setting. He wrote these theses in Latin, the language of the academy, and in them he attacked several of the main 
tenets of scholastic theology. He clearly expected that their publication and debate would cause a stir, allowing him to divulge 
his great discovery. But, much to his surprise, the theses and the debate on them aroused little interest beyond the university it- 
self. It seemed that the notion that the gospel was entirely other than was commonly thought, which Luther took to be of para- 
mount importance, was received with little more than a great yawn. 
Then the unexpected happened. Luther wrote another set of theses, also in Latin, with no expectation that they would have 
more impact than the previous ones. But someone translated them into German, and circulated them in an inexpensive edition. 
The result created such a stir that eventually all of Christendom was involved in its consequences. The reason for this very dif- 
ferent reaction was that these other theses—officially titled Ninety-Five Theses on the Power and Efficacy of Indulgences, now com- 
monly known as Luther’s Ninety-five Theses—attacked the sale of indulgences and its theological presuppositions. With little 
awareness of what he was doing, or whom he was attacking, Luther had spoken against plans for profit designed by very pow- 
erful lords and prelates. 
The particular sale of indulgences that prompted Luther’s protest had been authorized by Pope Leo X, and also involved the 
economic and political ambitions of the powerful house of Hohenzollern, which aspired to hegemony in Germany. One of its 
members, Albert of Brandenburg, was already in possession of two episcopal sees, and hoped to acquire the most important 
archbishopric in Germany, that of Mainz. He began negotiations with Leo X, one of the worst popes in an age filled with corrupt, 
avaricious, and indolent popes. The result was an agreement whereby, for the sum of ten thousand ducats, Albert could have 
what he requested. Since this was a considerable sum, the pope also authorized Albert to announce a great sale of indulgences 
in his territories, on the condition that half of the proceeds would be sent to the papal coffers. Leo was concerned with the need 
to refurbish Rome where, as a result of the Great Schism and of the warring inclinations of some of the popes of the Renais- 
sance, many beautiful buildings showed signs of neglect. One of his dreams was to finish building the Basilica of Saint Peter, 
begun earlier by Julius II, and for this he needed the funds that he hoped to receive from Albert’s sale of indulgences. Thus, the 
refurbishment of the great basilica that is now the pride of Roman Catholicism indirectly helped foment the Protestant Refor- 
mation. 
The man put in charge of the sale of indulgences in Germany was the Dominican John Tetzel, an unscrupulous man who was 
willing to make scandalous claims about his wares as long as such claims would help sales. Thus, for instance, Tetzel and his 
preachers were heard announcing that the indulgences that they sold made the sinner “cleaner than when coming out of bap- 
tism,” and “cleaner than Adam before the Fall,” and that “the cross of the seller of indulgences has as much power as the cross 
of Christ.” Those who wished to buy an indulgence for a loved one who was deceased were promised that, “as soon as the coin 
in the coffer rings, the soul from purgatory springs.” 
Such claims aroused the indignation of many among the learned, who knew that Tetzel and his preachers were misrepre- 
senting the doctrine of the church. Among humanists, who bemoaned the prevailing ignorance and superstition, Tetzel’s 
preaching was seen as another example of the deep corruption of the church. Others who were imbued with the growing Ger- 
man nationalist sentiment saw Tetzel’s campaign as one more instance in which Rome was fleecing the German people, exploit- 
ing their credulity in order to squander the results on feasts and luxury. But such sentiments were only quietly expressed, and 
the sale went on. 
It was at that point that Luther nailed his famous Ninety-five Theses to the door of the castle church in Wittenberg. His theses, 
written in Latin, were not calculated to cause a great religious commotion, as he had hoped would be the case with his earlier 
theses. After his previous experience, he seems to have thought that such issues were important only to theologians and that his 
new set of theses would not be read or debated beyond academic circles. But these Ninety-five Theses, written with a deep sense 
of righteous indignation, were much more devastating than the earlier ones. While addressing fewer theological issues, they did 
evoke a positive response from those who resented the exploitation of Germany by foreign interests—and by Germans such as 
the Hohenzollerns in connivance with those interests. Also, in concretely attacking the sale of indulgences, Luther was endan- 
gering the profits and designs of the pope and of the house of Hohenzollern. And, although his attack was relatively moderate, 
Luther went beyond the question of the efficacy of indulgences, and pointed to the exploitation that stood at the heart of it. Ac- 
cording to Luther: if it is true that the pope is able to free souls from purgatory, he ought to use that power, not for trivial rea- 
sons such as the building of a church, but simply out of love, and freely (thesis 82). In truth, the pope should give his money to 
the poor from whom the sellers of indulgences wring their last coins, and he ought to do this even if it were to require selling 
the Basilica of Saint Peter (thesis 51). 
 
 
A copy of one of the indulgences against which Luther protested. 
 
Luther published his theses on the Eve of All Saints, and their impact was such that that very date, October 31, 1517, is often 
said to mark the beginning of the Protestant Reformation. Printers soon spread copies of the Ninety-five Theses throughout Ger- 
many, in both their original Latin text and in a German translation. Luther sent a copy to Albert of Brandenburg personally, with 
a very respectful cover letter. Albert sent both the theses and the letter to Rome, asking Pope Leo to intervene. Emperor Maxim- 
ilian was enraged at the impertinence of the upstart friar, and he too asked Leo to silence Luther. Meanwhile, Luther published 
an extensive explanation of the theses, clarifying what he had meant in those very brief propositions, but sharpening his attack 
on indulgences, and expounding on parts of the theological stance on which he based his protest. 
The pope’s response was to ask the Augustinian Order to deal with the matter, for Luther was one of its members. The Re- 
former was called to the order’s next chapter meeting, in Heidelberg. He went in fear for his life, for he expected to be con- 
demned and burned as a heretic. But he was surprised to find that many of his fellow friars favored his teachings, and that some 
of the younger ones were even enthusiastic about it. Others saw the dispute between Luther and Tetzel as one more instance of 
the ancient rivalry between Dominicans and Augustinians, and therefore refused to abandon their champion. Eventually, Luther 
was able to return to Wittenberg, strengthened by the support of his order, and encouraged by those whom he had won to his 
cause. 
The pope then attempted a different tack. The Imperial Diet—the assembly of the princes and nobles—was scheduled to 
meet in Augsburg, with Emperor Maximilian presiding over it. As his legate to that gathering, Leo sent Cardinal Cajetan, a man 
of vast erudition whose main task was to convince the German princes to undertake a crusade against the Turks, who were 
threatening Western Europe, and to agree to a tax for the support of that enterprise. Fear of the Turkish threat was such that 
Rome was seeking reconciliation with the Hussites in Bohemia, and was even willing to accept some of the conditions they im- 
posed. As a secondary task, Cajetan was also instructed to meet with Luther and force him to recant. If the friar proved 
obstinate, he was to be sent as a prisoner to Rome. 
Luther’s ruling prince, Frederick the Wise, elector of Saxony, secured from Emperor Maximilian a safe-conduct for Luther. The 
latter, however, put little trust in the imperial word, remembering that little more than a century before, under similar circum- 
stances and in violation of an imperial safe-conduct, John Huss had been burned at Constance. But in spite of this, he went to 
Augsburg, convinced that he would not die unless God willed it. 
The meeting with Cajetan did not go well. The cardinal refused to discuss Luther’s teachings, and demanded that he simply 
recant. The friar, for his part, declared that he was willing to withdraw what he had said, if he could only be convinced that he 
was wrong. When he learned that Cajetan did not have to debate the issues at stake, because he was armed with the pope’s au- 
thority to arrest him, Luther secretly left Augsburg at night and returned to Wittenberg, where he issued an appeal to a general 
council. 
During all this time, Luther had been able to count on the protection of Frederick the Wise, Elector of Saxony and therefore 
the lord of Wittenberg. At this point, Frederick felt compelled to protect Luther, not because he was convinced of the truth of the 
friar’s teachings, but simply because justice demanded that he be given a hearing and a fair trial. Above all else, Frederick 
wished to be known and remembered as a wise and just ruler. With that end in mind, he had founded the University of Witten- 
berg, where many professors supported Luther, and told him that he was by no means a heretic. At least until Luther was duly 
judged and condemned, Frederick would protect him from the possibility of becoming a victim of a crime such as had been 
committed in the burning of John Huss. Such steadfastness on the elector’s part was not easy, for opposition was mounting, 
and the number and power of those who declared Luther to be a heretic were constantly increasing. 
At that point, Maximilian’s death left the imperial throne vacant. Since this was an elective honor, it was now necessary to set- 
tle on a successor to the dead emperor. The two most powerful candidates were Charles I of Spain and Francis I of France. The 
accession of either Charles or Francis to the imperial throne was feared by Pope Leo, whose policies would be threatened by the 
resulting concentration of power in a single person. Charles already had, besides Spain—rapidly becoming rich through the 
gold flowing from its colonial empire—vast hereditary possessions in Austria, the Low Countries—now the Netherlands, Bel- 
gium, and Luxembord—and southern Italy. Were the imperial crown to be placed on his brow, his power would be unrivaled in 
Western Europe. Francis of France, while not holding as much territory as Charles was also feared by Leo, for the union of the 
French and German crowns would place the papacy once again under the shadow of France. The pope therefore had to find an- 
other candidate worthy of support, not because of his power but by reason of his personal prestige. Given such criteria, the ideal 
candidate with whom the pope could oppose both Charles and Francis was Frederick the Wise of Saxony, who had earned the 
respect and admiration of other German princes. Were Frederick to be elected emperor, the resulting balance of power would 
allow Leo greater influence and independence. Therefore, even before Maximilian’s death, the pope had decided to court Fred- 
erick, and to select him as his candidate for emperor. 
But Frederick protected Luther, at least until the friar was properly tried and convicted. Therefore, Leo followed a policy of 
postponing the condemnation of Luther and seeking better relations both with the Reformer and with his protector. To seek 
such rapprochement, he sent Karl von Miltitz, a relative of Frederick, as his ambassador to Saxony. As a sign of special papal 
favor, Miltitz took with him a golden rose for Frederick. Although the pope refrained from sending a similar gift to Luther, he 
instructed his legate to approach the rebellious monk in a conciliatory manner. 
Miltitz met with Luther, who promised that he would abstain from further controversy as long as his opponents did likewise. 
This brought about a brief truce, which was broken by John Eck, a professor at the University of Ingolstadt who was incensed by 
Luther’s teachings. Eck was an astute opponent, and therefore instead of attacking Luther, which would have made him appear 
to have broken the existing peace, he attacked Andreas Rudolph Bodenstein von Karlstadt, another professor at Wittenberg. Karl- 
stadt had been converted to Luther’s position, but he was an impetuous man who was ready to carry his new beliefs to their rad- 
ical conclusions. This in itself made him more vulnerable than Luther to the charge of heresy, and therefore Eck was well ad- 
vised to challenge Karlstadt to a debate. This was to take place in Leipzig, and was originally billed as a discussion, not of 
Luther’s theses, but of Karlstadt’s theology. But the questions posed for debate were clearly those raised by Luther, and there- 
fore the Reformer declared that this was merely a subterfuge to attack him, and that he too would participate in the debate. 
The event was conducted with the strict formality of an academic debate and lasted for several days. When Luther and Eck fi- 
nally confronted each other, it was clear that the former had greater knowledge of Scripture, whereas the latter was more at 
home in canon law and medieval theology. Eck very ably maneuvered the discussion into his own field of expertise, and finally 
Luther felt compelled to declare that the Council of Constance had erred in condemning Huss, and that a Christian with the sup- 
port of Scripture has more authority than all popes and councils against that support. That sufficed. Luther had declared himself 
in agreement with a heretic who had been condemned by an ecumenical council, and had even dared accuse the council itself of 
having erred. In spite of the strength of Luther’s arguments, which bested Eck at a number of points, it was his rival who won 
the debate, for he had proven what he had set out to prove: that Luther was a heretic and a supporter of the teachings of Huss. 
Thus began a new stage in Luther’s struggle, marked by more open confrontations and greater dangers. But the Reformer and 
his followers had made good use of the time granted to them by political circumstances, with the result that throughout Ger- 
many, and even beyond its borders, there were increasing numbers who saw in Luther the champion of biblical faith. Events 
such as those that took place at the University of Ingolstadt were repeated throughout Germany. In Ingolstadt, the faculty sup- 
ported the arrest and exile of one of its younger members, on the grounds that he held Lutheran views. Soon there was uproar. 
Argula von Grumbach, a Bavarian noblewoman who had been converted to Luther’s views, and the first woman to publish 
Protestant treatises, came to the defense of the young professor in a blistering letter in which she showed herself more adept at 
theological debate than the learned faculty at Ingolstadt. In two months, there were twenty editions of her letter, which became a 
cause célèbre. While not always as dramatic, similar events shook practically every part of Germany. 
To those who found themselves in theological agreement with Luther was added the support of many humanists and German 
nationalists. The former saw many points of contact between Luther’s protest and the reformation that they proposed. The latter 
saw in him the mouthpiece of German outrage in the face of the abuses of Rome. 
 
 
The papal bull Exsurge Domine, calling Luther a wild boar and demanding his recantation. 
 
A few weeks before the Leipzig Debate, Charles I of Spain had been elected emperor, and was known thereafter as Charles V. 
Although Charles owed a debt of gratitude to Frederick the Wise for having supported his candidacy, he was a strictly orthodox 
man who would not countenance heresy in his lands, and therefore his election bode ill for Luther. Frederick still supported 
him—the more so since he was becoming increasingly convinced that the Reformer was right. But now the pope had no reason 
to delay a formal condemnation that had earlier been stayed only for political considerations. In the papal bull Exsurge Domine, 
in which Leo declared that a wild boar had entered the Lord’s vineyard, he ordered all books by Martin Luther to be burned; and 
he gave the rebellious friar, under the threat of the penalty of excommunication and the declaration of anathema, sixty days to 
submit to Roman authority. 
The bull took a long time to reach Luther. As copies of it arrived in various German territories, there were conflicting reac- 
tions. In some places, the pope’s instructions were obeyed, and there were public burnings of Luther’s books. But in other 
places students and other supporters of Luther chose to burn the works of his opponents. When the bull finally reached Luther, 
he burned it publicly, together with other books that he declared to be the worst proponents of “popish doctrines.” The breach 
was final, and there was no way to undo it. 
It was still necessary to determine the attitude of the emperor and the other German lords, for without their support there was 
little that Leo could do to silence the Reformer. The political maneuvers that took place in this regard were too complicated to 
retell here. Let it suffice to say that even Charles V, a convinced Catholic, showed himself willing to use Luther as a threat when 
he feared that Leo was showing too much favor for his rival, Francis I of France. Eventually, after much back and forth, it was de- 
cided that Luther would appear before the Imperial Diet to be gathered at Worms in 1521. 
At Worms, Luther was taken before the emperor and several of the great lords of the German Empire. The man in charge of 
the process showed him a number of books, and asked him if he had indeed written them. After examining them, Luther 
responded that such was the case, and that he had also written other books besides these. Then he was asked if he still held to 
what he had declared in those publications or wished to recant anything. This was a difficult moment for Luther, not so much 
because he feared imperial power but rather because he feared God. To dare to oppose the entire church and the emperor, 
whose authority had been ordained by God, was a dreadful act. Once again the friar trembled before the divine majesty, and 
asked for a day’s time in which to consider his answer. 
By the next day it was widely known that Luther was to appear before the Diet, and the hall was filled. The emperor’s presence 
at Worms, with a corps of Spanish soldiers who showed little respect for Germans, had irritated the populace as well as many 
German princes. Once again, Luther was asked to recant. In the midst of a great hush, the friar answered that much of what he 
had written was basic Christian doctrine, held by both him and his opponents, and that therefore no one should expect him to 
repudiate such teaching. At some other points, he continued, his works dealt with the tyranny and injustice that the German 
people suffered. This too he could not recant, for such was not the purpose of the Diet, and in any case to withdraw such words 
would result in greater injustice. Third, in his works there were attacks against certain individuals, and points of doctrine that 
were at issue between him and his opponents. Perhaps, he confessed, some of these things had been said too harshly. But their 
truth he could not deny, unless someone could convince him that he was in error. 
It was not the emperor’s purpose to engage in a debate on Luther’s teaching, and therefore he was asked once again, “Do you 
recant, or do you not?” To this Luther responded in German, therefore setting aside the Latin of traditional theological debate: 
“My conscience is a prisoner of God’s Word. I cannot and will not recant, for to disobey one’s conscience is neither just nor 
safe. God help me. Amen.”² Then, with a gesture of victory, he left the hall and returned to his quarters. 
In burning the papal bull, Luther had challenged Rome. Now, at Worms, he was challenging the empire. Therefore, he had 
ample reason to plead: “God help me!”



EXILE, UNREST, AND REBELLION 
By burning the papal bull, Luther had challenged the pope’s authority. At Worms, by refusing to recant, he challenged that of the 
emperor. The latter had no intention of allowing a rebellious friar to question his authority, and therefore was ready to take ac- 
tion against Luther, in spite of the safe-conduct Frederick the Wise had obtained for the Reformer. But several powerful mem- 
bers of the Diet opposed such action, and Charles was forced to negotiate with them. When the Diet finally acquiesced to the 
emperor’s wishes by promulgating the edict quoted above, Luther was nowhere to be found. 
What had happened was that Frederick the Wise, aware the emperor would demand that the Diet condemn Luther, had taken 
steps to ensure the Reformer’s safety. An armed band, following the elector’s instructions, had abducted Luther and taken him 
to Wartburg Castle. Based on his own instructions, Frederick was not informed and thus did not know where Luther had been 
hidden. Many thought him dead, and there were rumors that he had been killed by order of the pope or the emperor. 
Hidden at Wartburg, Luther grew a beard, sent word to some of his closest friends not to fear for him, and spent his time 
writing. His most significant work of this period was the German translation of the Bible. The translation of the New Testament, 
begun at Wartburg, was finished two years later; the Old Testament took ten years to be completed. But that work was well worth 
the time spent on it, for Luther’s Bible, besides adding impetus to the Reformation itself, shaped the German language and na- 
tional identity. 
While Luther was in exile, his collaborators in Wittenberg continued the work of reformation. Foremost among these were 
Karlstadt (who was mentioned earlier as a participant at the Leipzig Debate) and Philipp Melanchthon. The latter was a young 
professor of Greek whose temperament differed substantially from Luther’s but who was wholly convinced of the truth of his 
older colleague’s teachings. Until then, the reformation Luther advocated had not been implemented in the religious life of Wit- 
tenberg. Luther’s fear of God and of unwarranted innovation was such that he had hesitated to take the concrete steps that 
should follow from his doctrine. But now, while he was absent, several such steps were taken in rapid succession. A number of 
monks and nuns left their monastic communities and were married. Worship was simplified, and German was substituted for 
Latin. Masses for the dead were abolished, as were days of fasting and abstinence. Melanchthon also began to offer communion 
in both kinds—that is, to give the laity the cup as well as the host. 
At first, Luther supported these changes. But soon he began to question the excesses that were taking place at Wittenberg. 
When Karlstadt and several of his followers began tearing down images of saints in churches, Luther recommended moder- 
ation. Then three laymen appeared at Wittenberg from neighboring Zwickau, declaring themselves prophets. They claimed that 
God spoke directly to them, and that they therefore had no need for Scripture. Melanchthon was at a loss as to how to respond 
to such claims, and asked Luther’s advice. Finally, the latter decided that what was at stake was nothing less than the gospel it- 
self, and that he must return to Wittenberg. Before taking that step, he notified Frederick the Wise of his intentions, making it 
clear that he was returning to Wittenberg counting not on Frederick’s protection but on God’s. 
Although Luther was not one to take such matters into account when it was a question of obedience to God, political circum- 
stances favored him, making it possible for Frederick to keep him hidden at the Wartburg Castle, and later allowing him to re- 
turn to Wittenberg without being arrested and executed. Charles V was determined to stamp out the Lutheran “heresy.” But he 
was threatened by more powerful enemies, and could not allow himself the luxury of alienating those among his German 
subjects who supported Luther. Charles’s most constant rival was Francis I of France. The latter, who in earlier years had been 
the most influential sovereign in Europe, was not pleased at the rising star of Charles I of Spain, who now had become Charles 
V of the Holy Roman Empire, and who also held vast hereditary possessions that virtually surrounded France. Shortly before the 
Diet of Worms, the two rivals had clashed in Navarre. (As we shall see later, it was in that conflict that Ignatius Loyola received 
the wound that would eventually cause him to become one of the leaders of the Catholic Reformation.) From the year of the Diet 
(1521) until 1525, Charles was repeatedly at war with Francis. Finally, at the Battle of Pavia, the king of France was captured by 
imperial troops, and the conflict between the two most powerful monarchs in Western Europe seemed to have come to an end. 
 
 
Luther at the Diet of Worms. Bas-relief in the monument to the Reformation at Worms. 
 
Meanwhile, a few months before the Diet of Worms, Leo X had died, and Charles had used his influence to see that his tutor, 
Adrian of Utrecht, was elected pope. The new pope, who took the name of Adrian VI and was the last non-Italian pope until the 
twentieth century, was eager to reform the life of the church, but would brook no deviation from traditional orthodoxy. He 
brought austerity of life to Rome, and began a program of reformation that he hoped would respond to the critics of the church 
and steal Luther’s thunder. But Adrian died a year and a half after his election, and his program was abandoned. His successor, 
Clement VII, returned to Leo’s policies, for he too was more interested in the arts and in Italian politics than in ecclesiastical 
matters. Soon there was serious friction between him and the emperor, and this prevented the Catholic party from taking coordi- 
nated action against the German reformers. 
Charles V signed a peace treaty with his prisoner Francis, and on that basis restored him to freedom and to his throne. But 
the conditions to which Francis had been forced to agree were harsh, and once he was back in France he secured Clement’s 
support against Charles. The latter was eager to destroy Lutheranism and to put an end to the Turkish menace at his Eastern 
borders. Given the nature of these two causes, he hoped to be able to count on the support of France and the papacy. But just 
as he was preparing his campaign, both Francis and Clement declared war on him. 
In 1527, imperial troops, mostly Spanish and German, invaded Italy and marched on Rome. The city could not be defended, 
and the pope fled to the Castel Sant’Angelo, leaving the city to be sacked by the invaders. Since many of these were Lutheran, 
the sack of Rome took on religious overtones: God was finally punishing the Antichrist. The pope’s situation was desperate 
when, early in 1528, a French army, with English financial support, came to his aid. The imperial troops were forced to withdraw, 
and would have suffered great losses had an epidemic not forced the French to abandon their pursuit. In 1529, Charles agreed to 
peace, first with the pope, and then with Francis. 
Charles was once again preparing to take strong measures against the heretics in his German territories when the Turks, led 
by Suleiman, marched on Vienna, the capital of Charles’s Austrian territories. The fall of Vienna would leave Germany open to 
Turkish attack, and therefore the emperor and his German subjects set aside their religious differences and joined in a campaign 
against the Turks. The defenders of Vienna were resolute, and the city stood firm until the advancing German armies forced 
Suleiman to withdraw. 
It was then that, after a prolonged absence, Charles returned to Germany, with the clear intention of stamping out the Luther- 
an heresy. During the intervening years, however, several important events had taken place. In 1522 and 1523, there had been a 
rebellion of knights, under the leadership of Franz von Sickingen. The knightly class had seen its fortunes declining for some 
time and, among the landless and penniless knights, nationalist feelings ran high. Many blamed Rome for their ill fortune, and 
saw Luther as the champion of the German nation. Some, such as Ulrich von Hutten, were also convinced of the truth of 
Luther’s religious teachings but felt that the Reformer was too timid. When they finally rebelled, many claimed that they were 
doing so in defense of the Reformation, although Luther had done nothing to encourage them. The rebels attacked Trier, but 
were decisively defeated by the German princes, who took the opportunity to dispossess the lesser gentry of the few lands that 
still remained in their hands. Sickingen died in battle, and von Hutten fled to Switzerland, where he died shortly thereafter. All 
this was seen by Luther and his closest colleagues as a great tragedy, proving once again that one should submit to the estab- 
lished authorities. 
In 1524, a peasant rebellion broke out. For decades the conditions of the German peasantry had been worsening. As a result, 
there had been rebellions in 1476, 1491, 1498, 1503, and 1514. But none of these was as widespread or as devastating as the 
uprisings of 1524 and 1525. One of the elements making these rebellions particularly virulent was that they took on religious 
overtones, for many among the peasantry believed that the teachings of the reformers supported their economic demands. Al- 
though Luther himself refused to extend the application of his teachings to the political realm in terms of revolution, there were 
others who disagreed with him on that point. Foremost among these was Thomas Müntzer, a native of Zwickau, whose early 
teachings were similar to those of the “prophets” from his village who created such a stir in Wittenberg. Müntzer claimed that 
what was most important was not the written word of Scripture but the present revelation of the Spirit. In his case, such spiri- 
tualist doctrine had political consequences, for he felt that those who had been born again via the Spirit should join in a theo- 
cratic community to bring about the Kingdom of God. Luther had forced Müntzer out of Saxony, for he feared the consequences 
of his teachings. But the fiery preacher returned and joined the peasant rebellion. 
Even apart from Müntzer’s participation, this uprising had a measure of religious inspiration. In their Twelve Articles, the 
peasants made both economic and religious demands. They sought to base their claims on the authority of Scripture, and con- 
cluded by declaring that, if any of their demands was shown to be contrary to Scripture, it would be withdrawn. Therefore, al- 
though Luther himself could not see any relationship between his doctrines and the rebellion, the peasants themselves did see 
such relationship. 
In any case, Luther was at a loss as to what his attitude should be. Possibly his difficulties were related to his doctrine of the 
two kingdoms (see Chapter 4). When he first read the Twelve Articles, he addressed the princes, telling them that what was de- 
manded of them in the articles was just, for the peasants were sorely oppressed. But when the uprising broke out, and the peas- 
ants took up arms, Luther tried to persuade them to follow a more peaceful course, and finally called on the princes to suppress 
the movement. Later, when the rebellion was drowned in blood, he urged the victorious princes to be merciful. But his words 
were not heeded, and it is said that more than a hundred thousand peasants were killed. 
These events had fateful consequences for the Reformation. Catholic princes blamed Lutheranism for the rebellion, and from 
that time even the most moderate among them took measures against the spread of heresy in their territories. Vast numbers of 
peasants, convinced that Luther had betrayed them, either returned to the old faith or became Anabaptists (see Chapter 6). 
Although the peasant rebellion occupied much of his time, there was also turmoil in Luther’s personal life. Even though the 
law regarded such actions as crime, when a group of nuns in a nearby convent sent word that they had been convinced by 
Luther’s arguments, and sought his help in escaping from the convent, Luther did arrange for their escape. He then had to pro- 
vide for each of them by either finding a position in a household or arranging for marriage. One of the nuns, Katharina von Bora, 
proved reluctant to marry any of her suitors. Several of Luther’s friends suggested that he ought to marry. Katharina made it 
clear that there were only two men she would consider as potential husbands—and one of them was Dr. Luther. At first Luther 
joked about it. He was also reluctant to marry because at that point he believed that it was quite possible that he would soon 
have to die as a martyr. But eventually he agreed to marry Katharina. Although clearly shaped by the patriarchal attitudes of the 
time, their marriage was quite happy. There are many hints at humor in their relationship—she complained that Luther was a 
slob, and he agreed that he owed much to “my lord” Katharina. He would also comment at the strangeness of waking up in the 
morning to find a pair of pigtails on his pillow. They had six children, and they worked jointly at providing a home for them as 
well as for a number of orphans and students. Luther would say that his family was like a “small church,” and would rejoice in 
being part of it. Out of these experiences, and out of the life of the family, came the famous Table Talks that his students com- 
piled and published and which are one of the best avenues for insight into him as a man. His efforts to educate his children as 
well as others have been cited as a forerunner of public education. Furthermore, Luther’s family life became the model that 
many devout Germans would follow for generations. 
 
 
Katharina Von Bora 
 
But while Luther was learning how to be a husband and a father, Germany was undergoing ever greater turmoil, and Catholic 
moderates throughout Europe were forced to choose sides between Luther and his opponents. The most famous of the human- 
ists, Erasmus, had looked with favor on the early stages of the Lutheran movement but did not find the resultant discord much 
to his liking. He found controversy and dissension most repugnant, and would have preferred to stay out of the debate. But he 
was too famous to be allowed such a luxury and eventually was forced to take a stand. Although he had frequently criticized the 
ignorance and corruption of the clergy, he had never advocated a radical reformation in theology, and therefore, when forced to 
speak out, he was bound to take the side of Luther’s adversaries. 
Still, Erasmus preferred to choose his own field of battle. Therefore, instead of attacking Luther on such issues as justification 
by faith, the mass as a sacrifice, or the authority of the pope, he raised the issue of free will. Luther had been led to affirm the 
doctrine of predestination both because it was a corollary of justification by faith as a free gift of God, and because he found it 
amply supported by the authority of Paul and Augustine. It was on this point that Erasmus attacked him, publishing a treatise on 
free will. 
Luther responded by thanking Erasmus for having shown the wisdom to focus his attention on a fundamental issue and not 
on peripheral matters such as the sale of indulgences, the relics of the saints, and so on. But then he went on to defend his 
position with characteristic vehemence. As he saw matters, the notion of free will as held by pagan philosophers and by the 
moralists of his time did not take into account the enormous power of sin. Sin is such that we are powerless to be rid of it. Only 
by divine intervention can we be justified and freed from the power of evil. And even then we continue to be sinners. Therefore, 
when it comes to serving God, our much-vaunted free will can do nothing of itself. It is only by God’s initiative—by divine pre- 
destination—that we are justified. 
The controversy between Luther and Erasmus led many humanists to abandon the Lutheran cause. A few, such as Philipp 
Melanchthon, continued their staunch support of Luther while maintaining cordial relations with Erasmus and his friends. But 
these were by no means the majority, and therefore the controversy over predestination and free will marked the end of all hope 
for close collaboration between Lutherans and humanists. 



THE DIETS OF THE EMPIRE 
While all this was taking place, and in the emperor’s absence, it was necessary to govern the empire. Since Charles V had left the 
country almost immediately after the Diet of Worms, and since that diet’s edict against Luther had been the result of imperial 
pressure, nothing was done to enforce the decree against the reformer. When the Imperial Diet met again at Nuremberg, in 1523, 
it adopted a policy of tolerance toward Lutheranism, in spite of the protests of the legates of both pope and emperor. 
In 1526, when Charles was engaged in his struggles with Francis I of France and Pope Clement VII, the Diet of Spire formally 
withdrew the Edict of Worms, and granted each of the many German states the freedom to choose its own religious allegiance. 
Austria and many of the southern territories of Germany opted for Catholicism, while others began implementing the Lutheran 
Reformation. Germany had thus become a religious mosaic. 
In 1529, the Second Diet of Spire took a different tack. At that point there was renewed threat of imperial intervention, and 
princes who until then had been fairly moderate joined the ranks of the staunch Catholics. The result was that the Edict of 
Worms was reaffirmed. This prompted the Lutheran princes to present a formal protest, thus receiving the name of “Protes- 
tants.” 
Charles V finally returned to Germany in 1530, in order to attend the Diet of Augsburg. At Worms, the emperor had refused to 
listen to Luther’s arguments. But now, in view of the turn of events, he requested an orderly exposition of the points at issue. 
This document, whose main author was Philipp Melanchthon, is now known as the Augsburg Confession—and for a long time 
Lutherans commonly referred to themselves as “Christians of the Augsburg Confession.” When first drawn, it spoke only for the 
Protestants of Saxony. But other princes and leaders also signed it, and thus it was the instrument whereby most Protestants 
presented a united front before the emperor (although there were two other minority statements that disagreed on several points 
with Melanchthon’s document). When the signatories of the Augsburg Confession refused to abandon their faith, the emperor 
was enraged and ordered that they must recant by April of the following year, or suffer the consequences. 
The survival of Protestantism was threatened. If the emperor joined his hereditary resources from Austria, Spain, and other 
lands to those of the Catholic German princes, he would easily crush any Protestant prince who refused to recant. The Protes- 
tant princes decided that their only hope was to offer a common front. After long hesitation, Luther agreed that it was licit to take 
up arms in self-defense against the emperor. The Protestant territories then joined in the League of Schmalkalden, whose pur- 
pose was to resist the imperial edict if Charles sought to impose it by force of arms. 
 
 
Emperor Charles V listening to the Augsburg Confession while the rulers who signed it stand around him, each identified by his coat of 
arms. The scenes in the background represent various Lutheran services. Note that in Communion the people are receiving both the 
bread and the wine, and that blood flows from Christ’s side into the chalice. 
 
Both sides were making ready for long and cruel war when international events once more forced Charles to postpone action. 
Francis of France was again preparing for war, and the Turks were planning to avenge their earlier failure at the walls of Vienna. 
To counteract such powerful enemies, Charles needed a united Germany. These circumstances demanded negotiation rather 
than war, and finally Protestants and Catholics agreed to the Peace of Nuremberg, signed in 1532. This stipulated that Protes- 
tants would be allowed to practice their faith, but could not seek to extend it to other territories. The imperial Edict of Augsburg 
was suspended and, in return, the Protestants offered the emperor their support against the Turks. They also promised not to go 
beyond what they had declared to be their faith in the Augsburg Confession. Once more, political circumstances favored Protes- 
tantism, for it continued advancing into new territories in spite of the agreement of Nuremberg.


4 
 
Luther’s Theology 
 
The friends of the cross affirm that the cross is good and that works are bad, for through the cross works are undone and the 
old Adam, whose strength is in works, is crucified. 
MARTIN LUTHER 
 
At this point in the life of Luther, we must pause to consider his theology, the driving force that would determine much of the 
rest of his life. By 1521, when he appeared before the Diet of Worms, Luther had come to the main theological conclusions that 
would characterize the whole of his thought. After that time, he would primarily expand and elaborate on the main points that 
had led him to his position at Worms. Therefore, this seems to be the best point in our narrative at which to pause and discuss 
the basic themes of Luther’s theology. Earlier, while telling of his personal quest for salvation, we spoke of the doctrine of justifi- 
cation by faith. But this was by no means the totality of Luther’s theology.



THE WORD OF GOD 
As is commonly known, Luther sought to make the Word of God the starting point and the final authority for his theology. As a 
professor of Scripture, the Bible was for him of paramount importance, and it was in it that he found an answer to his anguished 
quest for salvation. But this does not mean that he was a rigid biblicist, for what he understood the “Word of God” to be was 
more than the words written in the Bible. 
In its primary sense, the Word of God is none other than God. This is supported by the first verses of the Gospel of John, 
where it is written that “in the beginning was the Word, and the Word was with God, and the Word was God.” The Bible itself de- 
clares that, strictly speaking, the Word of God is none other than God the Son, the Second Person of the Trinity, the Word who 
was made flesh and dwelt among us. Therefore, when God speaks, we are not simply given information; also, and above all, 
God acts. This is what is meant in the book of Genesis, where the Word of God is a creating force: “God said, let there be . . . 
and there was.” When God speaks, that which is uttered is also created. God’s Word, besides telling us something, creates 
something in us and in all creation. That creative and powerful Word is Christ, whose incarnation is both God’s greatest reve- 
lation and God’s greatest action. In Jesus, God was revealed to us. And also in Jesus, God overcame the powers of evil that had 
held us in subjection. God’s revelation is also God’s victory. 
Given this biblical understanding of the Word of God, what makes the Bible the Word of God is not that it is infallible, nor 
that it can serve as a source of authority for theological and religious debate. The Bible is the Word of God because in it Jesus, 
the Word incarnate, comes to us. Any who read the Bible and somehow do not find Jesus in it, have not encountered the Word 
of God. This was the reason why Luther, while insisting on the final authority of Scripture, could make deprecating comments 
about parts of it. The Epistle of James, for instance, seemed to him “pure straw,” because he could not find the gospel in it, but 
only a series of rules of conduct. The book of Revelation also caused him difficulty. Although he was not ready to delete such 
books from the canon, he openly confessed that it was difficult for him to see Jesus Christ in them, and that therefore they were 
of little value to him. 
This notion of the Word of God as Jesus Christ himself allowed Luther to respond to one of the main objections Catholics 
raised to his doctrine of the authority of Scripture above the church. They argued that, since it was the church that had deter- 
mined which books should be included in the canon of Scripture, it was clear that the church had authority over the Bible. 
Luther responded that it was neither the church that had made the Bible, nor the Bible that had made the church, but the gospel, 
Jesus Christ, that had made both the Bible and the church. Final authority rests neither in the church nor in the Bible, but in the 
gospel, in the message of Jesus Christ, who is the Word of God incarnate. Since Scripture gives a more trustworthy witness to 
that gospel than the pope’s corrupt church, or even the best in Christian tradition, the Bible has authority over church, pope, 
and tradition. This is so, even though it is also true that in the early centuries of Christianity it was the church that recognized 
the gospel in certain books, and not in others, and thus determined the actual content of the Bible.


THE THEOLOGY OF THE CROSS 
Luther had been formed in the tradition of late medieval theology, which had profound doubts about the ability of reason to 
investigate or to prove matters of faith. Even so, he agreed with most traditional theology that it is possible to know something 
about God by purely rational or natural means. Such knowledge includes the fact that God exists, and allows us to distinguish 
between good and evil. The pagan philosophers of antiquity had this knowledge, and it is clear from the laws of ancient Rome 
that they were able to distinguish between good and evil. Furthermore, the philosophers were able to conclude that there is a 
single Supreme Being from which all things draw their existence. 
But all this is not the true knowledge of God. As Luther would say, one does not get to know God by speculation, like one can 
get to the roof by climbing a ladder. All human efforts to climb to heaven, and thus to know God, are futile. Such efforts are 
what Luther calls “a theology of glory.” This theology seeks to know the divine being in itself, in its own glory, while ignoring the 
enormous distance between God and humans. In the final analysis, a theology of glory seeks God in those things that humans 
consider most valuable and praiseworthy, and that is why it is so concerned with the power of God, the glory of God, and the 
goodness of God. But this is little more than creating God after our own image, and we deceive ourselves into believing that 
God’s nature is what we would like it to be. 
The fact of the matter is that the God of revelation is very different from the God of a theology of glory. God’s highest self- 
disclosure takes place in the cross of Christ, and therefore Luther proposes, instead of a theology of glory, a “theology of the 
cross.” Such theology seeks God, not where we choose, nor as we would like God to be, but in the divine revelation of the cross. 
There God is seen in weakness, in suffering, as a stumbling block. This means that God acts in a radically different way than we 
would expect. In the cross, God destroys our preconceived notions of divine glory. When we know God in the cross, we must 
set aside our previous knowledge of God, that is, all that we thought we knew by means of reason or of the inner voice of con- 
science. What we now know of God is very different from the easily assumed knowledge of a theology of glory.	


It is in the divine revelation that God is truly known. But in that revelation God is made manifest in two ways: law and gospel. 
This does not mean simply that the law is first, and then the gospel. Nor does it mean that the Old Testament is law, and the 
New Testament is gospel. This is a misunderstanding that eventually led many Lutherans to consider Judaism and Jews as great 
enemies of the Christian faith, for they supposedly emphasized law, while Christianity is a matter of grace. It is true that Luther 
shared many—though not all—of the prejudices of his time against Jews. But for Luther, God is revealed in law and gospel in 
both the Old Testament and the New. The contrast between law and gospel shows that God’s revelation is both a word of judg- 
ment and a word of grace. The two always come together, and one cannot hear the word of grace without hearing also the word 
of judgment. 
The doctrine of justification by faith, the message of God’s forgiveness, does not imply that God is indifferent to sin. It is not 
simply that God forgives us because after all our sin is not of great consequence. On the contrary, God is holy, and sin is repug- 
nant to the divine holiness. When God speaks, we are overwhelmed by the contrast between such holiness and our own sin. 
That is what Luther means by the Word of God as law. 
But God also speaks a word of forgiveness—a forgiveness so tied up with the divine holiness that sometimes the same word 
is both judgment and grace. That forgiveness is the gospel, made all the more joyful and overpowering because the judgment of 
the law is so crushing. This gospel does not contradict or obliterate the law. God’s forgiveness does not deny the gravity of our 
sin. It is precisely that gravity that makes the gospel such surprising good news. 
When we hear that word of pardon, however, the character of the law changes for us. What earlier seemed an unbearable 
weight now becomes bearable and even sweet. Commenting on the Gospel of John, Luther declares: 
 
At an earlier time there was no pleasure in the law for me. But now I find that the law is good and tasty, that it has been given 
to me so that I might live, and now I find my pleasure in it. Earlier, it told me what I ought to do. Now I begin to adapt myself 
to it. And for this I worship, praise, and serve God.³



THE CHURCH AND SACRAMENTS 
Contrary to common belief, Luther was neither an individualist nor a rationalist. During the nineteenth century, when both ratio- 
nalism and individualism seemed to be the wave of the future, some historians sought to depict Luther as the forerunner of 
such currents. This was frequently tied to an effort to show that Germany was the mother of modern civilization, of the use of 
reason, and of individual freedom. In such interpretations, Luther became the great national hero of Germany, the founder of 
modernity. 
But all this is far removed from historical truth. The fact of the matter is that Luther was far from being a rationalist. His fre- 
quent references to reason as “dirty” or “a whore”—which reflect his upbringing in late medieval theology—should suffice to 
prove this point. As to his supposed individualism, this was more characteristic of the Italian leaders of the Renaissance than of 
the German Reformer; and, in any case, Luther attached too much importance to the church to be classified as a true individ- 
ualist. 
In spite of his protest against commonly accepted doctrine, and despite his rebellion against the authorities of the Roman 
church, Luther was convinced that the church was an essential element of the Christian message. His theology was not that of 
an individual in direct communion with God, but rather of a Christian life to be lived within a community of believers, and this 
community he frequently called “mother church.” 
While it is true that all Christians, by virtue of their baptism, are priests, this does not mean—as some later interpreters have 
said—that one is self-sufficient to approach God for oneself. There is a direct communion with God that all Christians can and 
should enjoy. But there is also an organic reality within which all communion with God takes place, and that reality is the 
church. To be priests does not mean primarily that we are our own individual priests, but rather that as part of the priestly peo- 
ple of God we are priests for the entire community of belief, and that they are priests for us—while all of us, as the believing 
community, are priests for the world. Rather than setting aside the need for the community of the church, the doctrine of the 
universal priesthood of believers strengthens it. It is true that access to God is no longer controlled by a hierarchical priesthood. 
But we still stand in need of the community of believers, the body of Christ, in which each member is a priest for the rest, and 
feeds the rest. Without such nourishment, an isolated member cannot live. 
In that community, all have a place or a vocation, and all occupations—as long as they are honest and godly—are equally 
valuable before the eyes of God. The monastic life is no holier or worthier than the life of a ruler or of a cobbler, for all con- 
tribute to God’s designs and order. With this assertion, which is usually called “the sanctity of the common life,” Luther opened 
the way for the modern sense of vocation—although, being a man of his time, he generally felt that each one’s calling was 
generally determined by birth. It would be in the next generation, with Calvin and his contemporaries, that a sense of vocation 
providing opportunities to move into new walks of life would come to the foreground. 
Within the life of that church, the Word of God comes to us in the sacraments. For a rite to be a true sacrament, it must have 
been instituted by Christ, and it must be a physical sign of the promise of the gospel. Applying such criteria, Luther comes to 
the conclusion that there are only two sacraments: baptism and communion. Other rites and ceremonies that are commonly 
called sacraments, although perhaps beneficial, ought not to be considered sacraments of the gospel—although for a time 
Luther did consider the possibility of declaring penance to also be a sacrament. 
Baptism is first of all a sign of the believer’s death and resurrection with Jesus Christ. But it is much more than a sign, for by 
its power we are made members of the body of Christ. Baptism and faith are closely tied, for the rite itself without faith is not 
valid. But this does not mean that one must have faith before being baptized, or that infants born in the church but as yet inca- 
pable of faith ought not to be baptized. To come to such a conclusion, Luther declares, would be to fall into the error of believ- 
ing faith to be a human work, something we must do, and not a free gift of God. In salvation, the initiative is always God’s, and 
this is precisely what the church proclaims in baptizing infants who are incapable of understanding what is taking place. Fur- 
thermore, baptism is not only the beginning of the Christian life but also the foundation and the context in which the entire life 
of the believer takes place. Baptism is valid, not only when it is received but throughout life. That is why we are told that Luther 
himself, when he felt sorely tried, was wont to exclaim, “I am baptized.” In his own baptism lay the strength to resist the powers 
of evil. 
Communion is the other Christian sacrament. Luther rejected a great deal of commonly accepted doctrine regarding commu- 
nion. He was particularly opposed to the celebration of private masses, to the understanding of communion as a repetition of 
the sacrifice of Calvary, to the notion that there are “merits” in simply attending mass, to the doctrine of transubstantiation, and 
to the “reservation” of the sacrament—the claim that the body of Christ remains present in the bread even after the celebration 
of communion is over. But, in spite of his opposition to what he saw as the misuse and misinterpretation of communion, he 
continued to attach great importance to the sacrament itself, and to the presence of Christ in it. While insisting on the need for 
the preached Word, he retained the Word made visible in communion as the center of Christian worship. 
The question of the manner in which Christ is present in communion gave rise to long debates, not only with Catholics, but 
also among Protestants. Luther categorically rejected the doctrine of transubstantiation, which he saw as unduly tied to Aris- 
totelian—and therefore pagan—metaphysics. Also, the manner in which the doctrine of transubstantiation had been used had 
tied it to the theory that the mass was a meritorious sacrifice, and this ran contrary to justification by faith. 
On the other hand, Luther was not ready to reduce communion to a mere sign or symbol of spiritual realities. He took Jesus’ 
words at the institution of the sacrament as very clear and undeniable proof of his physical presence at the sacrament: “this is 
my body.” Therefore, Luther felt compelled to affirm that in communion one truly and literally partakes of the body of Christ. 
This need not imply, as with transubstantiation, that the bread and wine become body and blood. The bread is still bread, and 
the wine is still wine. But now the body and blood of the Lord are also with them, and the believer is nourished by that body and 
that blood through the very act of eating the bread and drinking the wine. Although later interpreters have commonly used the 
term consubstantiation to describe Luther’s doctrine of the presence of Christ in communion in contrast to Roman Catholic 
transubstantiation, Luther never used such metaphysical terms, but would speak of the presence of the body of Christ in, with, 
under, around, and behind the bread and wine. 
Not all who opposed traditional doctrine agreed with Luther on these points, and this soon gave rise to conflicts among lead- 
ers of the Reformation. Karlstadt, Luther’s colleague at the University of Wittenberg who debated Eck at Leipzig, claimed that the 
presence of Christ in communion was merely symbolic, and that when Jesus said “this is my body” he was pointing to himself 
and not the bread. Ulrich Zwingli (who is discussed in Chapter 5) held similar views although with better arguments. As we shall 
see, when they met at Marburg in 1529, this was the one point on which they could not agree. Eventually, the question of how 
Christ is present in communion became one of the main points at issue in the debates between Lutherans and Reformed. 



THE TWO KINGDOMS 
Before concluding this brief overview of Luther’s theology, a word must be said regarding the relationship between church and 
state. According to Luther, God has established two kingdoms: one under the law, and the other under the gospel. The state 
must operate under the law, and its main purpose is to set limits to human sin and its consequences. Without the state, sin 
would lead to chaos and destruction. Believers, on the other hand, belong to the other kingdom, which is under the gospel. This 
means that Christians ought not to expect the state to be ruled by the gospel, nor to support orthodoxy by persecuting heretics. 
Furthermore, there is no reason why Christians should require that the state be ruled by fellow believers in order to obey them. 
Rulers, as such, must follow the law, and not the gospel. In the kingdom of the gospel, civil authorities have no power. In that 
which refers to this second kingdom, Christians are not subject to the state, and owe it no allegiance. But one must always 
remember that believers are at once justified and sinners; therefore, as people who are still sinners, we are under the authority of 
the state. 
In concrete terms, this meant that true faith should not seek to impose itself by means of civil authority, but only through the 
power of the Word. In the complex realities of power and politics, however, such principles were difficult to follow. Luther re- 
peatedly rejected offers of help from the princes who had embraced his cause, and yet found himself being helped by them. 
When those who had embraced the Reformation were threatened by Catholic armies, Luther hesitated on a proper response, but 
eventually agreed with the Lutheran princes that they were justified in going to war in self-defense. Similarly, in the case of the 
peasants’ revolt, Luther held that the peasants were being treated unjustly, but that as Christians they still had no right to revolt. 
Over the centuries, Luther’s understanding of the relationship between the church and the civil order has repeatedly affected the 
manner in which his followers have dealt with oppressive or unjust governments, which has not been as radical as has been the 
case with those of the Reformed (or Calvinist) tradition. 
 
 
This Lutheran caricature shows the bitterness of the struggle between Catholics and Protestants. Note the pope sitting on his throne at 
the very mouth of Hades, and the devils crowning him. 
 
Luther was not a pacifist. Being subject to the law, the state can take up arms when circumstances and justice so demand. 
When the Turks threatened to overrun Christendom, Luther advised his followers to take up arms. And when he became con- 
vinced that certain movements, such as the peasant uprisings and Anabaptism (see Chapter 6), were subversive, he declared 
that civil authorities were under obligation to crush them. He had serious doubts regarding the traditional understanding of the 
relationship between church and state. But his own doctrine of the two kingdoms, on which he sought to base his actions in the 
political arena, was difficult to apply to concrete situations.



