---
title: "Linear Algebra"
format: html
date: 1/4/2023
toc: true
---

-   Systems of linear equations

-   Is_Linear when Scalar $\times$ variable $=$ variable

-   Linear: $2x_{1}-3x_{2}+5x_{3}=9$

-   Non-Linear: $2\sqrt{x_{1}}+3x_{2}=5$

-   Non-Linear: $x_{1}^{2}+x_{2}^{2}=3$

-   Linear: $ex_{1}+\pi{}x_{2}=\sqrt{2}$

Linear when scalar times variable only. Not variable times variable.

-   Linear. System of equations:

    -   $x_{1}+x_{2}+x_{3}=1$
    -   $2x_{1}-3x_{2}+2$

Augmented means it has a solution? An equal sign? an \| ?

<br>

## Solving Outcome Possibiblities

Options are either: $0$, $1$, or $\inf{}$

**Existence**: Does there exist a solution?

**Uniqueness**: Is there only one solution?

Remember those rules we learned in Pre-Algebra? Those are coming into play right now. 

- **Replacement**: Replace one row by the sum of itself and a multiple of another row
    - Example: $R_{2} \rightarrow R_{2}+-2R_{1}$
- **Interchange**: Interchange two rows
- **Scaling**: Multiply all the entries in arow by a nonzero constant
    - Example: $R_{2} \rightarrow \frac{-1}{5}R_{2}$


<br>

Vocab:

- Reduced Row Echelon Form