---
title: 1.3 Vector Equations
format: html
---

<center>

## Section 1.3 Vector Equations

</center>


### Vectors in $\mathbb{R}^{2}$

- matrices with only one column is called a **vector**. Examples:
    - $u = \left[ \matrix{3 \\ -1} \right]$
    - $v = \left[ \matrix{.2 \\ .3} \right]$
    - $w = \left[ \matrix{w_{2} \\ w_{3}} \right]$ where $w_{2}$ and $w_{3}$ are any real numbers 
- The set of al vectors wih two entries is denoted by $\mathbb{R}^{2}$ (read as "r-two"). 
- Summing vectors is done horizontally (adding row-wise): 

$$
\left[ \matrix{1 \\ 2} \right] + \left[ \matrix{2 \\ 5} \right] = \left[ \matrix{1 + 2 \\ -2 + 5} \right] = \left[ \matrix{3 \\ 3} \right]
$$

Given a vector u and a real number c, the scalar multiple of u by c is the vector cu
obtained by multiplying each entry in u by c. Example: 
$$
\text{if} u = \left[ \matrix{3 \\ -1} \right] \text{and } c = 5, \text{then } cu = 5\left[\matrix{3 \\ -1} \right] = \left[ \matrix{15 \\ -5 } \right] 
$$


### Geometric Descriptions of $\mathbb{R}^{2}$

- Some graphical depictions I am not 100% confortble with yet

### Vectors in $\mathbb{R}^{3}$ 

$\mathbb{R}^{3}$ means $3 \times{} 1$ column matrices with three entries. 

**This means 3D coordinate space!**



### Vectors in $\mathbb{R}^{n}$

I assume this means *n-dementional* space 


This is the collection of all lists (or ordered n-tuples) of n real numbers

$\mathbb{R}^{n}$ means the vector is $n \times{} 1$ 

> Remember X means rows and Y means column(s) 

> row(s) $\times{}$ column(s)


$$
u = \left[ \matrix{u_{1} \\ u_{2} \\ . \\ . \\ . \\ u_{n}} \right]
$$


### Linear Combinations

- Vectors are represented as **v** in $\mathbb{R}^{n}$
- Scalers are represented as $c_{1}, c_{2}, ..., c_{p}$, often called **weights**
- putting this together, we get an **linear combination**: $y=c_{1}v_{1} + \dots{} + c_{p}v_{p}$
- Here is an application of the linear combination formula: $\sqrt{3}v_{1} + v_{2} \text{, } \frac{1}{2}v_{1}(=\frac{1}{2}v_{1}+0v_{2}) \text{, and } 0(-0v_{1}+0v_{2})$
- some things I'm unfamiliar with are: parallelogram rule, linear combinations to the fundamental existance question (from 1.1)

Scalar multiplication and vector addition example using $\textbf{a}_{1} = \left[ \matrix{1\\-2\\-5} \right], \textbf{a}_{2} = \left[\matrix{2\\5\\6} \right], \textbf{b} = \left[ \matrix{7\\4\\-3} \right]$. 

Our equation is $x_{1}\textbf{a}_{1} + x_{2}\textbf{a}_{2} = \textbf{b}$ 

We are going to find out the weights that make this true using #linearalgebra


$$
x_{1} \left[ \matrix{1\\-2\\-5} \right] + x_{2}\left[ \matrix{2\\5\\6} \right] = \left[ \matrix{7\\4\\-3} \right] 
$$

$$
\left[ \matrix{ x_{1} \\ -2x_{1} \\ -5x_{1} } \right] + \left[ \matrix{ 2x_{2} \\ 5x_{2} \\ 6x_{2} } \right] = \left[ \matrix{7 \\ 4 \\ -3} \right]
$$

$$
\left[ \matrix{ x_{1} + 2x_{2} \\ -2x_{2} + 5x_{2} \\ -5x_{1} + 6x_{2} } \right] = \left[ \matrix{7 \\ 4 \\ -3} \right]
$$

$$
\matrix{ x_{1} &+ 2x_{2} &= 7 \\ -2x_{1} &+ 5x_{2} &= 4 \\ -5x_{1} &+ 6x_{2} &= -3}
$$

Now row reduce until it is fully simplified

> $\sim{}$ means "is similar to" according to LaTex. According to the textbook it means "row equivalence"

$$
\left[ \matrix{1 & 2 & 7 \\ -2 & 5 & 4 \\ -5 & 6 & -3} \right] \sim{} \left[ \matrix{1 & 2 & 7 \\ 0 & 9 & 18 \\ 0 & 16 & 32 \\} \right] \sim{} \left[ \matrix{1 & 2 & 7 \\ 0 & 1 & 2 \\ 0 & 16 & 32} \right] \sim{} \left[ \matrix{1 & 0 & 3 \\ 0 & 1 & 2 \\ 0 & 0 & 0} \right]
$$

This means $x_{1} = 3$ and $x_{2} = 2$. Take a look below: 

$$
3\left[ \matrix{1 \\ -2 \\ -5} \right] + 2\left[ \matrix{2 \\ 5 \\ 6} \right] = \left[ \matrix{7 \\ 4 \\ -3} \right]
$$


There are a small amount of more things that I'm close to understanding but not quite yet: 

- span 
- difference between $c_{p}$ and $v_{p}$
- what does $\textbf{b}$ exactly mean?

### A Geometric Description of Span ${v}$ and Span ${u, v}$

I'm having a difficult time understanding the concept of *scalar multiples*

- chatgpt says "In linear algebra, a scalar multiple is a product of a scalar (a real or complex number) and a vector. A scalar multiple of a vector can be thought of as a vector that has been multiplied by a scalar."

Span is something like when refering to $\textbf{b}$ (the x value that causes the solution to exist), is it in the values of the vectors given. 

### Linear Combinations in Applications

This gives a very simple $x * y = z$ ( number of units times cost per unit = total cost). 