---
title: Homework 1.1
format: html
toc: false
---

Assigned Problems: 1, 5, 9, 19, 23, 24, 31

Optional Problems: 2, 7, 13, 17


## Exercises 

Solve each system in Exercises 1–4 by using elementary row operations on the equations or on the augmented matrix. Follow the systematic elimination procedure described in this section.

### Q1

$$
\textbf{Question: }
\begin{array}{}
    x_{1} + 5x_{2} = 7 \\ 
    -2x_{1} - 7x_{2} = -5 
\end{array}
$$

:::{.callout-note collapse="true"}
# Steps

::: columns
::: {.column width="20%"}
$$
\textbf{Step 1: }
$$
$$
\text{Turn system of equations} 
$$
$$
\text{ into augmented matrix}
$$
:::
::: {.column width="80%"}
$$
\begin{bmatrix}
     1 &  5 & | &  7 \\ 
    -2 & -7 & | & -5
\end{bmatrix}
$$
:::
:::

<!-- Q1 Step 2 -->
::: columns
::: {.column width="20%"}
$$
\textbf{Step 2: } R_{2} \rightarrow 2R_{1} + R_{2} 
$$
:::
::: {.column width="80%"}
$$
\begin{bmatrix}
    1 & 5 & | & 7 \\
    0 & 3 & | & 9
\end{bmatrix}
$$
:::
:::

<!-- Q1 Step 3 -->
::: columns
::: {.column width="20%"}
$$
\textbf{Step 3: } R_{2} \rightarrow \frac{1}{3} R_{2}
$$
:::
::: {.column width="80%"}
$$
\begin{bmatrix}
    1 & 5 &|& 7 \\
    0 & 1 &|& 3
\end{bmatrix}
$$
:::
:::

<!-- Q1 Step 4 -->
::: columns
::: {.column width="20%"}
$$
\textbf{Step 4: } R_{1} \rightarrow R_{1} + (R_{2} \times -5) 
$$
:::
::: {.column width="80%"}
$$
\begin{bmatrix}
    1 & 0 &|& -8 \\
    0 & 1 &|&  3
\end{bmatrix}
$$
:::
:::

<!-- ending callout-note -->
::: 
<!-- ending callout-note -->

<!-- Q1 Solution -->
$$
\textbf{Solution: } 
\begin{array}{}
    x_{1} = -8 \\
    x_{2} = 3
\end{array}
$$

### Q2: Optional

$$
\textbf{Question: }
\begin{array}{}
    2x_{1} + 4x_{2} = -4 \\
    5x_{1} + 7x_{2} = 11
\end{array}
$$

:::{.callout-note collapse="true"}
# Steps 

<!-- Q2 Step 1 -->
::: columns
::: {.column width="20%"}
$$
\textbf{Step 1: } 
$$
$$
\text{Turn system of equations} 
$$
$$
\text{ into augmented matrix}
$$
:::
::: {.column width="80%"}
$$
\begin{bmatrix}
    2 & 4 &|& -4 \\ 
    5 & 7 &|& 11
\end{bmatrix}
$$
:::
:::

<!-- Q2 Step 2 -->
::: columns
::: {.column width="20%"}
$$
\textbf{Step 2: } R_{2} \rightarrow \frac{1}{2} R_{2} 
$$
:::
::: {.column width="80%"} 
$$
\begin{bmatrix}
    1 & 2 &|& -2 \\ 
    5 & 7 &|& 11
\end{bmatrix}
$$
:::
:::

<!-- Q2 Step 2 -->
::: columns
::: {.column width="20%"}
$$
\textbf{Step 2: } R_{2} \rightarrow R_{1} \times -5 + R_{2}
$$
:::
::: {.column width="80%"}
$$
\begin{bmatrix}
    1 &  2 & | & -2 \\ 
    0 & -3 & | & 21
\end{bmatrix}
$$
:::
:::

<!-- Q2 Step 3 -->
::: columns
::: {.column width="20%"}
$$
\textbf{Step 3: } R_{2} \rightarrow \frac{-1}{3} R_{2} 
$$
:::
::: {.column width="80%"}
$$
\begin{bmatrix}
    1 & 2 & | & -2 \\ 
    0 & 1 & | & -7
\end{bmatrix}
$$
:::
:::

<!-- Q2 Step 4 -->
::: columns
::: {.column width="20%"}
$$
\textbf{Step 4: } R_{2} \rightarrow R_{2} \times -2 + R_{1}
$$
::: 
::: {.column width="80%"}
$$
\begin{bmatrix}
    1 & 0 & | & 12 \\ 
    0 & 1 & | & -7
\end{bmatrix}
$$
:::
:::

<!-- ending callout note -->
:::
<!-- ending callout note -->

<!-- Q2 Solution -->
$$
\textbf{Solution: } 
\begin{array}{}
    x_{1} = 12 \\
    x_{2} = -7
\end{array}
$$

----

Consider each matrix in Exercises 5 & 6 as the augmented matrix of a linear system. State in words the next two elementry row operations that should be preformed in the process of solving the system.

### Q5

$$
\begin{bmatrix} 
    1 & -4 &  5 & 0 &|&  7 \\ 
    0 &  1 & -3 & 0 &|&  6 \\ 
    0 &  0 &  1 & 0 &|&  2 \\
    0 &  0 &  0 & 1 &|& -5
\end{bmatrix}
$$


:::{.callout-note collapse="true"}
# Steps

<!-- Q5 Step 1 -->
::: columns
::: {.column width="20%"}
$$
\textbf{Step 1: } R_{1} \rightarrow R_{1} + (4 \times R_{2})
$$
:::
::: {.column width="80%"}
$$
\begin{bmatrix}
    1 & 0 & -2 & 0 &|&  31 \\ 
    0 & 1 & -3 & 0 &|&  6 \\ 
    0 & 0 &  1 & 0 &|&  2 \\
    0 & 0 &  0 & 1 &|& -5
\end{bmatrix}
$$
:::
:::

<!-- Q4 Step 2 -->
::: columns
::: {.column width="20%"}
$$
\textbf{Step 2: } R_{2} \rightarrow (R_{3} \times 3) + R_{2} 
$$
:::
::: {.column width="80%"}
$$
\begin{bmatrix}
    1 & 0 & -2 & 0 &|&  49 \\ 
    0 & 1 &  0 & 0 &|&  6 \\ 
    0 & 0 &  1 & 0 &|&  2 \\
    0 & 0 &  0 & 1 &|& -5
\end{bmatrix}
$$
:::
:::

<!-- Q5 Step 3 -->
::: columns
::: {.column width="20%"}
$$
\textbf{Step 3: } R_{1} \rightarrow (R_{3} \times 2) + R_{1}
$$
:::
::: {.column width="80%"}
$$
\begin{bmatrix}
    1 & 0 &  0 & 0 &|& 53 \\ 
    0 & 1 &  0 & 0 &|&  6 \\ 
    0 & 0 &  1 & 0 &|&  2 \\
    0 & 0 &  0 & 1 &|& -5
\end{bmatrix}
$$
:::
:::

<!-- ending callout note -->
:::
<!-- ending callout note -->

----

In Exercises 7–10, the augmented matrix of a linear system has
been reduced by row operations to the form shown. In each case,
continue the appropriate row operations and describe the solution
set of the original system.

### Q7: Optional


$$
\left[
    \matrix{
        1 & 7 & 3 & | & -4 \\
        0 & 1 & -1 & | & 3 \\
        0 & 0 & 0 & | & 1 \\
        0 & 0 & 1 & | & -2 
    }
\right]
$$


### Q9

$$ 
\left[
    \matrix{1 & -1 & 0 & 0 & | & -4 \\ 
            0 & 1 & -3 & 0 & | & -7 \\ 
            0 & 0 & 1 & -3 & | & -1 \\
            0 & 0 & 0 & 2 & | & 4}
\right]
$$

----

Solve the systems in Exercise 11-14.

### Q13

$$
\array{
    &x_{1} &- &3x_{2} &&&= 5 \\
    &-x_{1} &+ &x_{2} &+ &5x_{3} &= 2 \\
    &&&x_{2} &+ &x_{3} &= 0
}
$$

----

### Q17: Optional

Do the three lines $x_{1} + 2x_{2} + x_{3} = 4$, $x_{2} - x_{3} = 1$, and $x_{1} + 3x_{2} = 0$ have at least one common point of intersection? Explain. 

----

In Exercises 19–22, determine the value(s) of *h* such that the matrix is the augmented matrix of a consistent linear system.

### Q19

$$
\left[
    \matrix{1 & h & | & 4 \\
            3 & 6 & | & 8}
\right]
$$

----

In Exercises 23 and 24, key statements from this section are either quoted directly, restated slightly (but still true), or altered in some way that makes them false in some cases. Mark each statement True or False, and justify your answer. (If true, give the approximate location where a similar statement appears, or refer to a definition or theorem. If false, give the location of a statement that has been quoted or used incorrectly, or cite an example that shows the statement is not true in all cases.) Similar true/false questions will appear in many sections of the text. 

### Q23

a. Every elementry row operaion is reversible. 

b. A 5 $\times{}$ 6 matrix has six rows. 

c. The solution set of a linear system involving variables $x_{1},...,x_{n}$ is a list of numbers $\left(s_{1},...,s_{n}\right)$ that makes each equation in the system a true statement when the values $s_{1},...,s_{n}$ are substituted for $x_{1},...,x_{n}$, respectively. 

d. Two fundamental questions about a linear system involve existence and uniqueness. 

### Q24

a. Elementry row operations on an augmented matrix never change the solution set of the associated linear system

b. Two matrices are row equivalent if they have the same number of rows 

c. An inconsistent system has more than one solution. 

d. Two linear systems are equivalent if they have the same solution set. 

----

In Exercises 29–32, find the elementary row operation that transforms the first matrix into the second, and then find the reverse row operation that transforms the second matrix into the first.

### Q31

$$
\left[
    \matrix{
        1 & -2 & 1 & | & 0 \\
        0 & 5 & -2 & | & 8 \\
        4 & -1 & 3 & | & -6
    }
\right], 
\left[
    \matrix{
        1 & -2 & 1 & | & 0 \\
        0 & 5 & -2 & | & 8 \\
        0 & 7 & -1 & | & -6
    }
\right]
$$

